// Rol ruxsatlari katalogi (Modme uslubida — bo'limlar bo'yicha)
export interface Tri { uz: string; ru: string; en: string }
export interface PermGroup { group: Tri; items: { key: string; label: Tri }[] }

const g = (key: string, label: Tri) => ({ key, label });

export const PERM_GROUPS: PermGroup[] = [
  { group: { uz: "Bosh ekran", ru: "Главный экран", en: "Home screen" }, items: [g("home.branch", { uz: "Administrator filiali", ru: "Филиал администратора", en: "Administrator branch" }), g("home.chat", { uz: "Suhbat", ru: "Чат", en: "Chat" }), g("home.dashboard", { uz: "Dashboard", ru: "Дашборд", en: "Dashboard" })] },
  { group: { uz: "Topshiriqlar", ru: "Задачи", en: "Tasks" }, items: [g("tasks.staff", { uz: "Xodim topshiriqlari", ru: "Задачи сотрудников", en: "Staff tasks" }), g("tasks.tasks", { uz: "Vazifalar", ru: "Задачи", en: "Tasks" })] },
  { group: { uz: "Lidlar", ru: "Лиды", en: "Leads" }, items: [g("leads.orderStatus", { uz: "Buyurtma holati", ru: "Статус заказа", en: "Order status" }), g("leads.order", { uz: "Buyurtma", ru: "Заказ", en: "Order" })] },
  { group: { uz: "Guruh", ru: "Группа", en: "Group" }, items: [g("group.lesson", { uz: "Guruh mashg'uloti", ru: "Занятие группы", en: "Group lesson" }), g("group.rooms", { uz: "Xonalar", ru: "Кабинеты", en: "Rooms" }), g("group.viewStudents", { uz: "Guruhda o'quvchilarni ko'ra olish", ru: "Просмотр учеников в группе", en: "View students in group" }), g("group.group", { uz: "Guruh", ru: "Группа", en: "Group" }), g("group.attendance", { uz: "Guruh davomati", ru: "Посещаемость группы", en: "Group attendance" }), g("group.schedule", { uz: "Dars jadvali", ru: "Расписание занятий", en: "Class schedule" })] },
  { group: { uz: "O'quvchilar", ru: "Ученики", en: "Students" }, items: [g("students.student", { uz: "O'quvchi", ru: "Ученик", en: "Student" }), g("students.bonus", { uz: "Bonus", ru: "Бонус", en: "Bonus" }), g("students.adminKpi", { uz: "Adminlar KPI", ru: "KPI администраторов", en: "Admins KPI" })] },
  { group: { uz: "Gamifikatsiya", ru: "Геймификация", en: "Gamification" }, items: [g("gam.gam", { uz: "Gamifikatsiya", ru: "Геймификация", en: "Gamification" })] },
  { group: { uz: "O'quv bo'limi", ru: "Учебный отдел", en: "Education department" }, items: [g("edu.seasonal", { uz: "Mavsumiy baholash", ru: "Сезонное оценивание", en: "Seasonal assessment" }), g("edu.level", { uz: "Daraja", ru: "Уровень", en: "Level" }), g("edu.category", { uz: "O'quvchi kategoriyasi", ru: "Категория ученика", en: "Student category" }), g("edu.direction", { uz: "Ta'lim yo'nalishi", ru: "Направление обучения", en: "Education direction" }), g("edu.course", { uz: "Kurs", ru: "Курс", en: "Course" }), g("edu.contract", { uz: "Shartnoma", ru: "Договор", en: "Contract" }), g("edu.online", { uz: "Onlayn kurs", ru: "Онлайн-курс", en: "Online course" })] },
  { group: { uz: "Moliya", ru: "Финансы", en: "Finance" }, items: [g("fin.analytics", { uz: "Moliya analitikasi", ru: "Финансовая аналитика", en: "Finance analytics" }), g("fin.teacherSalary", { uz: "O'qituvchi oyligi", ru: "Зарплата преподавателя", en: "Teacher salary" }), g("fin.cashTx", { uz: "Kassa tranzaksiyasi", ru: "Кассовая транзакция", en: "Cash transaction" }), g("fin.recurring", { uz: "Takroriy xarajatlar", ru: "Повторяющиеся расходы", en: "Recurring expenses" }), g("fin.cash", { uz: "Kassa", ru: "Касса", en: "Cash register" })] },
  { group: { uz: "Nazorat", ru: "Контроль", en: "Control" }, items: [g("control.feedback", { uz: "Fikr-mulohaza", ru: "Обратная связь", en: "Feedback" })] },
  { group: { uz: "Boshqaruv", ru: "Управление", en: "Management" }, items: [g("mgmt.role", { uz: "Rol", ru: "Роль", en: "Role" }), g("mgmt.staff", { uz: "Xodimlar", ru: "Сотрудники", en: "Staff" }), g("mgmt.branch", { uz: "Filial", ru: "Филиал", en: "Branch" })] },
  { group: { uz: "Sotuv va marketing", ru: "Продажи и маркетинг", en: "Sales and marketing" }, items: [g("sm.smsTpl", { uz: "SMS shablonlari", ru: "SMS-шаблоны", en: "SMS templates" }), g("sm.survey", { uz: "Marketing so'rovnomasi", ru: "Маркетинговый опрос", en: "Marketing survey" }), g("sm.news", { uz: "Yangiliklar", ru: "Новости", en: "News" }), g("sm.salesPlan", { uz: "Savdo plani", ru: "План продаж", en: "Sales plan" }), g("sm.sms", { uz: "SMS", ru: "SMS", en: "SMS" })] },
  { group: { uz: "Hisobotlar", ru: "Отчёты", en: "Reports" }, items: [g("rep.analytics", { uz: "Analitika", ru: "Аналитика", en: "Analytics" }), g("rep.conversion", { uz: "Konversiya hisobotlari", ru: "Отчёты по конверсии", en: "Conversion reports" }), g("rep.attendance", { uz: "Davomat hisobotlari", ru: "Отчёты по посещаемости", en: "Attendance reports" })] },
];

export const ALL_PERM_KEYS: string[] = PERM_GROUPS.flatMap((gr) => gr.items.map((i) => i.key));
