// Daraja aniqlash testi — SAVOLLAR BANKI.
//
// Manba: markazning o'z test to'plamlari (A1.1 ×2, A2.1, A2.2, B1.1, B1,
// B2.1, B2 — 2026-09). To'plamlarda javob kaliti yo'q edi — `answer`
// grammatika bo'yicha belgilangan. Takror savollar chiqarib tashlangan,
// A2.1 №9 ("Ich fahre morgen ___ Berlin" — variantlarda "nach" yo'q edi)
// tuzatilgan.
//
// Har urinishda har darajadan PER_LEVEL ta savol TASODIFIY tanlanadi
// (src/lib/levelTest.ts → sampleLevelTest). Bu fayl faqat serverda
// o'qiladi — `answer` mijozga bormaydi.
//
// id: A1 → 1xx, A2 → 2xx, B1 → 3xx, B2 → 4xx.

import type { LevelTestQuestion } from "./levelTest";

export const LEVEL_TEST_BANK: LevelTestQuestion[] = [
  // ───────────────────────────── A1 ─────────────────────────────
  { id: 101, level: "A1", topic: "Begrüßung", q: "Du kommst am Morgen in die Schule. Was sagst du?", options: ["Gute Nacht!", "Guten Morgen!", "Gute Reise!", "Guten Appetit!"], answer: 1 },
  { id: 102, level: "A1", topic: "Personalpronomen", q: "___ heiße Anna.", options: ["Ich", "Du", "Er", "Sie"], answer: 0 },
  { id: 103, level: "A1", topic: "Verb „sein“", q: "Ich ___ Maria.", options: ["bist", "ist", "bin", "sind"], answer: 2 },
  { id: 104, level: "A1", topic: "Verb „sein“", q: "Du ___ Student.", options: ["bin", "bist", "ist", "sind"], answer: 1 },
  { id: 105, level: "A1", topic: "Verb „haben“", q: "Ich ___ ein Handy.", options: ["bist", "habe", "hat", "haben"], answer: 1 },
  { id: 106, level: "A1", topic: "Artikel", q: "___ Mann ist nett.", options: ["Die", "Das", "Der", "Eine"], answer: 2 },
  { id: 107, level: "A1", topic: "Artikel", q: "___ Frau heißt Anna.", options: ["Der", "Die", "Das", "Ein"], answer: 1 },
  { id: 108, level: "A1", topic: "Wortschatz", q: "Was ist das? 🥛", options: ["das Wasser", "die Milch", "der Kaffee", "der Saft"], answer: 1 },
  { id: 109, level: "A1", topic: "Zahlen", q: "Wie viel ist „zehn“?", options: ["5", "10", "15", "20"], answer: 1 },
  { id: 110, level: "A1", topic: "Farben", q: "Welche Farbe hat eine Banane normalerweise?", options: ["blau", "schwarz", "gelb", "weiß"], answer: 2 },
  { id: 111, level: "A1", topic: "Präsens", q: "Ich ___ Deutsch.", options: ["lerne", "lernst", "lernt", "lernen"], answer: 0 },
  { id: 112, level: "A1", topic: "Präsens", q: "Er ___ in Berlin.", options: ["wohnen", "wohnst", "wohnt", "wohne"], answer: 2 },
  { id: 113, level: "A1", topic: "Präsens", q: "Wir ___ in Taschkent.", options: ["wohnt", "wohnen", "wohnst", "wohne"], answer: 1 },
  { id: 114, level: "A1", topic: "Personalpronomen", q: "Anna ist meine Freundin. ___ ist sehr nett.", options: ["Er", "Es", "Sie", "Wir"], answer: 2 },
  { id: 115, level: "A1", topic: "Negation", q: "Ich bin ___ müde.", options: ["kein", "keine", "nicht", "nein"], answer: 2 },
  { id: 116, level: "A1", topic: "Negation", q: "Ich habe ___ Auto.", options: ["nicht", "kein", "keine", "nein"], answer: 1 },
  { id: 117, level: "A1", topic: "Possessivartikel", q: "Das ist ___ Buch.", options: ["ich", "mein", "meine", "mich"], answer: 1 },
  { id: 118, level: "A1", topic: "Akkusativ", q: "Ich habe ___ Bruder.", options: ["ein", "einen", "eine", "einem"], answer: 1 },
  { id: 119, level: "A1", topic: "Modalverb", q: "Ich ___ Deutsch sprechen.", options: ["kann", "kannst", "können", "gekannt"], answer: 0 },
  { id: 120, level: "A1", topic: "Satzstruktur", q: "Welche Variante ist richtig?", options: ["Ich Deutsch lerne.", "Deutsch ich lerne.", "Ich lerne Deutsch.", "Lerne Deutsch ich."], answer: 2 },
  { id: 121, level: "A1", topic: "Frage", q: "Welche Frage ist richtig?", options: ["Wie heißt du?", "Wie du heißt?", "Wie heißen du?", "Heißt wie du?"], answer: 0 },
  { id: 122, level: "A1", topic: "Dialog", q: "„Woher kommst du?“ — Was passt?", options: ["Ich bin 20 Jahre alt.", "Ich komme aus Usbekistan.", "Ich wohne in Berlin.", "Ich heiße Anna."], answer: 1 },
  { id: 123, level: "A1", topic: "Dialog", q: "Jemand fragt: „Wie geht es dir?“ — Was passt?", options: ["Ich komme aus Usbekistan.", "Ich bin Student.", "Danke, sehr gut.", "Ich bin 20 Jahre alt."], answer: 2 },
  { id: 124, level: "A1", topic: "Im Café", q: "Du möchtest einen Kaffee bestellen. Was sagst du?", options: ["Ich heiße Ali.", "Ich möchte einen Kaffee, bitte.", "Woher kommst du?", "Wie alt bist du?"], answer: 1 },
  { id: 125, level: "A1", topic: "Verabschiedung", q: "Du gehst nach Hause. Was kannst du sagen?", options: ["Guten Morgen!", "Guten Appetit!", "Auf Wiedersehen!", "Danke schön!"], answer: 2 },
  { id: 126, level: "A1", topic: "Artikel", q: "___ Tisch ist groß.", options: ["Die", "Der", "Das", "Eine"], answer: 1 },
  { id: 127, level: "A1", topic: "Verb „sein“", q: "Ich ___ Studentin.", options: ["habe", "bist", "bin", "ist"], answer: 2 },
  { id: 128, level: "A1", topic: "Verb „haben“", q: "Wir ___ ein Haus.", options: ["sind", "haben", "hat", "seid"], answer: 1 },
  { id: 129, level: "A1", topic: "Präsens", q: "Anna ___ in Berlin.", options: ["wohnen", "wohnst", "wohnt", "wohne"], answer: 2 },
  { id: 130, level: "A1", topic: "Wortschatz", q: "Was ist das? 🍎", options: ["die Banane", "der Apfel", "die Orange", "das Brot"], answer: 1 },
  { id: 131, level: "A1", topic: "Zahlen", q: "Wie viel ist „zwanzig“?", options: ["12", "20", "30", "22"], answer: 1 },
  { id: 132, level: "A1", topic: "Wochentage", q: "Welcher Tag kommt nach Montag?", options: ["Sonntag", "Freitag", "Dienstag", "Mittwoch"], answer: 2 },
  { id: 133, level: "A1", topic: "Uhrzeit", q: "08:00 Uhr — Wie sagt man das?", options: ["Es ist acht Uhr.", "Es ist achtzehn Uhr.", "Es ist sieben Uhr.", "Es ist neun Uhr."], answer: 0 },
  { id: 134, level: "A1", topic: "Artikel", q: "Ich habe ___ Tasche.", options: ["ein", "eine", "einen", "der"], answer: 1 },
  { id: 135, level: "A1", topic: "Negation", q: "Das ist ___ mein Buch.", options: ["kein", "nicht", "keine", "nein"], answer: 1 },
  { id: 136, level: "A1", topic: "Plural", q: "Das ist ein Kind. → Das sind zwei ___.", options: ["Kinds", "Kinder", "Kinders", "Kind"], answer: 1 },
  { id: 137, level: "A1", topic: "Possessivartikel", q: "Das ist ___ Mutter.", options: ["ich", "mein", "meine", "mich"], answer: 2 },
  { id: 138, level: "A1", topic: "Präsens", q: "Wir ___ jeden Morgen Kaffee.", options: ["trinken", "trinkt", "trinkst", "getrunken"], answer: 0 },
  { id: 139, level: "A1", topic: "Modalverb", q: "Ich ___ Deutsch lernen.", options: ["kann", "können", "kannst", "gekannt"], answer: 0 },
  { id: 140, level: "A1", topic: "Wortschatz", q: "Was macht man in einem Supermarkt?", options: ["Man kauft ein.", "Man schläft.", "Man arbeitet im Krankenhaus.", "Man schwimmt."], answer: 0 },
  { id: 141, level: "A1", topic: "Präposition", q: "Ich komme ___ Deutschland.", options: ["mit", "aus", "bei", "an"], answer: 1 },
  { id: 142, level: "A1", topic: "Satzstruktur", q: "Welche Satzstruktur ist richtig?", options: ["Ich jeden Tag Deutsch lerne.", "Deutsch ich lerne jeden Tag.", "Ich lerne jeden Tag Deutsch.", "Jeden ich Tag Deutsch lerne."], answer: 2 },
  { id: 143, level: "A1", topic: "Frage", q: "Welche Frage ist richtig?", options: ["Wo du wohnst?", "Wo wohnst du?", "Wo du wohnen?", "Wohnst wo du?"], answer: 1 },
  { id: 144, level: "A1", topic: "Ja-/Nein-Frage", q: "___ du aus Usbekistan?", options: ["Bist", "Ist", "Sind", "Sein"], answer: 0 },
  { id: 145, level: "A1", topic: "Präsens", q: "Am Montag ___ ich Deutsch.", options: ["lernen", "lernst", "lerne", "lernt"], answer: 2 },
  { id: 146, level: "A1", topic: "Dialog", q: "Du möchtest jemanden kennenlernen. Was sagst du?", options: ["Wie heißen Sie?", "Guten Appetit!", "Gute Nacht!", "Gute Reise!"], answer: 0 },
  { id: 147, level: "A1", topic: "Dialog", q: "Jemand sagt: „Danke!“ Was antwortest du?", options: ["Guten Morgen!", "Bitte!", "Entschuldigung!", "Gute Nacht!"], answer: 1 },
  { id: 148, level: "A1", topic: "Frage", q: "Wie ___ du?", options: ["heiße", "heißt", "heißen", "heiß"], answer: 1 },
  { id: 149, level: "A1", topic: "Artikel", q: "Das ist ___ Buch.", options: ["eine", "einen", "ein", "einer"], answer: 2 },
  { id: 150, level: "A1", topic: "Präsens", q: "Wir ___ nach Berlin.", options: ["fahre", "fährst", "fährt", "fahren"], answer: 3 },
  { id: 151, level: "A1", topic: "Frage", q: "___ du Kaffee?", options: ["Trinkt", "Trinke", "Trinken", "Trinkst"], answer: 3 },

  // ───────────────────────────── A2 ─────────────────────────────
  { id: 201, level: "A2", topic: "Perfekt", q: "Ich ___ gestern einen Kaffee ___.", options: ["habe … getrunken", "bin … getrunken", "habe … trinken", "bin … trinken"], answer: 0 },
  { id: 202, level: "A2", topic: "Perfekt", q: "Wir ___ am Wochenende einen Film ___.", options: ["sind … gesehen", "haben … gesehen", "haben … sehen", "sind … sehen"], answer: 1 },
  { id: 203, level: "A2", topic: "Modalverb", q: "Ich ___ heute leider nicht kommen.", options: ["kann", "kannst", "können", "gekonnt"], answer: 0 },
  { id: 204, level: "A2", topic: "Akkusativ", q: "Ich kaufe ___ neuen Computer.", options: ["ein", "einen", "einem", "einer"], answer: 1 },
  { id: 205, level: "A2", topic: "Dativ", q: "Ich helfe ___ Freund bei den Hausaufgaben.", options: ["mein", "meinen", "meinem", "meiner"], answer: 2 },
  { id: 206, level: "A2", topic: "Possessivartikel", q: "Das ist ___ Schwester.", options: ["mein", "meine", "meinen", "meinem"], answer: 1 },
  { id: 207, level: "A2", topic: "Trennbare Verben", q: "Ich ___ jeden Morgen um 7 Uhr ___.", options: ["stehe … auf", "aufstehe … —", "stehe auf … —", "auf … stehe"], answer: 0 },
  { id: 208, level: "A2", topic: "Reflexives Verb", q: "Ich ___ jeden Morgen.", options: ["dusche mich", "mich dusche", "dusche mir", "mich duschen"], answer: 0 },
  { id: 209, level: "A2", topic: "Präposition", q: "Ich fahre morgen ___ Berlin.", options: ["nach", "in", "an", "bei"], answer: 0 },
  { id: 210, level: "A2", topic: "Präposition", q: "Am Wochenende treffe ich mich ___ meiner Freundin.", options: ["für", "mit", "ohne", "durch"], answer: 1 },
  { id: 211, level: "A2", topic: "Konnektor „weil“", q: "Ich bleibe zu Hause, ___ ich krank bin.", options: ["aber", "oder", "weil", "und"], answer: 2 },
  { id: 212, level: "A2", topic: "Satzstellung", q: "Welche Variante ist richtig?", options: ["Weil ich krank bin, bleibe ich zu Hause.", "Weil ich bin krank, bleibe ich zu Hause.", "Weil krank ich bin, ich bleibe zu Hause.", "Weil ich krank bin, ich zu Hause bleibe."], answer: 0 },
  { id: 213, level: "A2", topic: "Konnektor „dass“", q: "Ich glaube, ___ er heute keine Zeit hat.", options: ["weil", "dass", "wenn", "aber"], answer: 1 },
  { id: 214, level: "A2", topic: "Konnektor „wenn“", q: "___ ich frei habe, gehe ich gern spazieren.", options: ["Weil", "Dass", "Wenn", "Aber"], answer: 2 },
  { id: 215, level: "A2", topic: "Präteritum", q: "Gestern ___ das Wetter sehr schön.", options: ["ist", "war", "hatte", "ist gewesen"], answer: 1 },
  { id: 216, level: "A2", topic: "Präteritum", q: "Früher ___ ich ein kleines Fahrrad.", options: ["habe", "bin", "hatte", "war"], answer: 2 },
  { id: 217, level: "A2", topic: "Vergleich", q: "Meine Schwester ist ___ als ich.", options: ["groß", "größer", "am größten", "mehr groß"], answer: 1 },
  { id: 218, level: "A2", topic: "Wortschatz", q: "Was bedeutet „mieten“?", options: ["etwas kaufen", "etwas für eine bestimmte Zeit gegen Geld benutzen", "etwas verkaufen", "etwas reparieren"], answer: 1 },
  { id: 219, level: "A2", topic: "Wortschatz", q: "Was bedeutet „abholen“?", options: ["jemanden oder etwas an einem Ort holen", "etwas bezahlen", "etwas vergessen", "etwas erklären"], answer: 0 },
  { id: 220, level: "A2", topic: "Satzstruktur", q: "Welche Satzstruktur ist richtig?", options: ["Ich habe gestern meine Hausaufgaben gemacht.", "Ich gestern habe meine Hausaufgaben gemacht.", "Ich habe gemacht gestern meine Hausaufgaben.", "Gestern ich habe meine Hausaufgaben gemacht."], answer: 0 },
  { id: 221, level: "A2", topic: "Konnektor", q: "Ich kann heute nicht kommen, ___ ich arbeiten muss.", options: ["aber", "weil", "und", "oder"], answer: 1 },
  { id: 222, level: "A2", topic: "Dialog", q: "Du möchtest jemanden um Hilfe bitten. Was passt?", options: ["Kannst du mir bitte helfen?", "Du hilfst mir!", "Ich helfe dir gestern.", "Du musst gestern helfen."], answer: 0 },
  { id: 223, level: "A2", topic: "Dialog", q: "Du möchtest einen Termin vereinbaren. Was sagst du?", options: ["Wann hast du gestern gearbeitet?", "Ich möchte gern einen Termin vereinbaren.", "Ich habe keinen Termin gehabt.", "Der Termin war gestern."], answer: 1 },
  { id: 224, level: "A2", topic: "Dialog", q: "Jemand fragt: „Was hast du gestern gemacht?“", options: ["Ich gehe morgen einkaufen.", "Ich möchte morgen einkaufen gehen.", "Ich habe gestern eingekauft.", "Ich kaufe gerade ein."], answer: 2 },
  { id: 225, level: "A2", topic: "Meinung", q: "Du möchtest deine Meinung einfach ausdrücken. Was passt?", options: ["Ich finde diese Idee gut.", "Obwohl diese Idee gut ist.", "Deshalb diese Idee gut.", "Wenn diese Idee gut."], answer: 0 },
  { id: 226, level: "A2", topic: "Perfekt", q: "Ich ___ gestern einen Film ___.", options: ["habe … gesehen", "bin … gesehen", "habe … sehen", "habe … sieht"], answer: 0 },
  { id: 227, level: "A2", topic: "Perfekt mit „sein“", q: "Wir ___ gestern nach Berlin ___.", options: ["haben … gefahren", "sind … gefahren", "sind … fahren", "haben … fahren"], answer: 1 },
  { id: 228, level: "A2", topic: "Modalverb im Präteritum", q: "Als Kind ___ ich viel spielen.", options: ["kann", "konnte", "gekonnt", "können"], answer: 1 },
  { id: 229, level: "A2", topic: "Dativ", q: "Ich helfe ___ Mutter.", options: ["meine", "meiner", "meinen", "mein"], answer: 1 },
  { id: 230, level: "A2", topic: "Dativ", q: "Ich gebe ___ Kind einen Ball.", options: ["der", "den", "dem", "das"], answer: 2 },
  { id: 231, level: "A2", topic: "Wortschatz", q: "Was bedeutet „besichtigen“?", options: ["etwas anschauen", "etwas kaufen", "etwas verkaufen", "etwas vergessen"], answer: 0 },
  { id: 232, level: "A2", topic: "Satzstellung", q: "Weil ich morgen arbeiten muss, ___ ich heute zu Hause.", options: ["bleibe", "ich bleibe", "bleibe ich", "ich bleiben"], answer: 0 },
  { id: 233, level: "A2", topic: "Konnektor „wenn“", q: "___ ich Zeit habe, besuche ich meine Freundin.", options: ["Wenn", "Weil", "Dass", "Deshalb"], answer: 0 },
  { id: 234, level: "A2", topic: "Präteritum", q: "Gestern ___ ich sehr müde.", options: ["bin", "war", "habe", "hatte"], answer: 1 },
  { id: 235, level: "A2", topic: "Präteritum", q: "Früher ___ ich kein Auto.", options: ["bin", "war", "hatte", "habe"], answer: 2 },
  { id: 236, level: "A2", topic: "Präposition", q: "Ich fahre morgen ___ meiner Freundin nach Hamburg.", options: ["mit", "für", "ohne", "durch"], answer: 0 },
  { id: 237, level: "A2", topic: "Adjektiv", q: "Das Wetter ist heute sehr ___.", options: ["schön", "schöne", "schöner", "schönes"], answer: 0 },
  { id: 238, level: "A2", topic: "Wortschatz", q: "Wenn man krank ist, geht man normalerweise zum ___.", options: ["Bäcker", "Arzt", "Bahnhof", "Supermarkt"], answer: 1 },
  { id: 239, level: "A2", topic: "Satzstruktur", q: "Welche Satzstruktur ist richtig?", options: ["Ich habe gestern meine Freundin getroffen.", "Ich gestern habe meine Freundin getroffen.", "Ich habe getroffen gestern meine Freundin.", "Gestern ich meine Freundin habe getroffen."], answer: 0 },
  { id: 240, level: "A2", topic: "Dialog", q: "„Warum lernst du Deutsch?“ — Welche Antwort passt?", options: ["Weil ich in Deutschland arbeiten möchte.", "Wenn ich in Deutschland arbeiten möchte.", "Dass ich in Deutschland arbeiten möchte.", "Deshalb ich in Deutschland arbeiten möchte."], answer: 0 },
  { id: 241, level: "A2", topic: "Konnektor „obwohl“", q: "Welche Variante ist richtig?", options: ["Obwohl es regnet, gehe ich spazieren.", "Obwohl es regnet, ich gehe spazieren.", "Obwohl regnet es, gehe ich spazieren.", "Obwohl es regnet, ich spazieren gehe."], answer: 0 },
  { id: 242, level: "A2", topic: "Konnektor", q: "Ich habe keine Zeit, ___ ich heute viel arbeiten muss.", options: ["aber", "denn", "weil", "trotzdem"], answer: 2 },
  { id: 243, level: "A2", topic: "Höflichkeit", q: "Du möchtest höflich um etwas bitten. Was passt?", options: ["Gib mir das!", "Ich hätte gern ein Glas Wasser, bitte.", "Du musst mir das geben.", "Ich nehme das sofort!"], answer: 1 },
  { id: 244, level: "A2", topic: "Dialog", q: "Jemand fragt: „Was hast du am Wochenende gemacht?“", options: ["Ich habe meine Freunde getroffen.", "Ich treffe meine Freunde morgen.", "Ich werde meine Freunde treffen.", "Ich möchte meine Freunde treffen."], answer: 0 },
  { id: 245, level: "A2", topic: "Meinung", q: "Du bist mit einem Vorschlag nicht einverstanden. Was passt am besten?", options: ["Das finde ich eine gute Idee.", "Ja, natürlich.", "Ich glaube, das ist keine gute Idee.", "Das möchte ich sehr gern."], answer: 2 },
  { id: 246, level: "A2", topic: "Perfekt", q: "Gestern ___ ich ins Kino gegangen.", options: ["habe", "war", "bin", "hatte"], answer: 2 },
  { id: 247, level: "A2", topic: "Akkusativ", q: "Ich habe ___ Auto gekauft.", options: ["eine", "ein", "einen", "einem"], answer: 1 },
  { id: 248, level: "A2", topic: "Konnektor „weil“", q: "Er kommt nicht, ___ er krank ist.", options: ["denn", "aber", "weil", "oder"], answer: 2 },
  { id: 249, level: "A2", topic: "Präposition", q: "Ich freue mich ___ das Wochenende.", options: ["über", "auf", "an", "für"], answer: 1 },
  { id: 250, level: "A2", topic: "Vergleich", q: "Das Buch ist ___ als der Film.", options: ["interessant", "am interessantesten", "interessanter", "interessantesten"], answer: 2 },
  { id: 251, level: "A2", topic: "Dativ", q: "Kannst du ___ helfen?", options: ["ich", "mich", "mein", "mir"], answer: 3 },

  // ───────────────────────────── B1 ─────────────────────────────
  { id: 301, level: "B1", topic: "Perfekt", q: "Gestern ___ ich meine Freunde getroffen.", options: ["habe", "bin", "werde", "hatte"], answer: 0 },
  { id: 302, level: "B1", topic: "Präteritum", q: "Früher ___ ich jeden Tag mit dem Bus zur Schule.", options: ["fahre", "fuhr", "gefahren", "fahre ich"], answer: 1 },
  { id: 303, level: "B1", topic: "Konnektor „weil“", q: "Ich lerne Deutsch, ___ ich in Deutschland arbeiten möchte.", options: ["aber", "weil", "trotzdem", "deshalb"], answer: 1 },
  { id: 304, level: "B1", topic: "Konnektor „deshalb“", q: "Ich bin heute krank. ___ bleibe ich zu Hause.", options: ["Obwohl", "Weil", "Deshalb", "Aber"], answer: 2 },
  { id: 305, level: "B1", topic: "Modalverb im Präteritum", q: "Als Kind ___ ich nicht lange draußen bleiben.", options: ["kann", "konnte", "gekonnt", "könnte"], answer: 1 },
  { id: 306, level: "B1", topic: "Reflexives Verb", q: "Ich ___ jeden Morgen auf die Arbeit.", options: ["bereite mich vor", "mich bereite vor", "bereite vor mich", "vor mich bereite"], answer: 0 },
  { id: 307, level: "B1", topic: "Präposition", q: "Ich interessiere mich sehr ___ Sport.", options: ["an", "für", "mit", "bei"], answer: 1 },
  { id: 308, level: "B1", topic: "Präposition", q: "Wir warten schon seit einer Stunde ___ den Bus.", options: ["auf", "an", "für", "mit"], answer: 0 },
  { id: 309, level: "B1", topic: "Relativsatz", q: "Das ist der Mann, ___ neben mir wohnt.", options: ["den", "dem", "der", "das"], answer: 2 },
  { id: 310, level: "B1", topic: "Relativsatz", q: "Das ist das Buch, ___ ich gestern gekauft habe.", options: ["der", "die", "das", "dem"], answer: 2 },
  { id: 311, level: "B1", topic: "Konjunktiv II", q: "Ich ___ gern mehr Deutsch sprechen.", options: ["würde", "werde", "wurde", "bin"], answer: 0 },
  { id: 312, level: "B1", topic: "Höfliche Bitte", q: "___ Sie mir bitte helfen?", options: ["Werden", "Würden", "Wurden", "Haben"], answer: 1 },
  { id: 313, level: "B1", topic: "Konnektor „wenn“", q: "___ ich Zeit habe, besuche ich meine Großeltern.", options: ["Obwohl", "Wenn", "Deshalb", "Trotzdem"], answer: 1 },
  { id: 314, level: "B1", topic: "Satzstellung", q: "Welche Variante ist richtig?", options: ["Weil ich heute arbeiten muss, kann ich nicht kommen.", "Weil ich muss heute arbeiten, kann ich nicht kommen.", "Weil heute ich arbeiten muss, kann ich nicht kommen.", "Weil ich heute arbeiten muss, ich kann nicht kommen."], answer: 0 },
  { id: 315, level: "B1", topic: "Konnektor „obwohl“", q: "___ es regnet, gehen wir spazieren.", options: ["Deshalb", "Weil", "Obwohl", "Wenn"], answer: 2 },
  { id: 316, level: "B1", topic: "Perfekt mit „sein“", q: "Letztes Wochenende ___ wir nach Samarkand gefahren.", options: ["haben", "sind", "werden", "waren"], answer: 1 },
  { id: 317, level: "B1", topic: "Wortschatz", q: "Was bedeutet „sich entscheiden“?", options: ["etwas vergessen", "eine Wahl treffen", "etwas kaufen", "etwas verlieren"], answer: 1 },
  { id: 318, level: "B1", topic: "Wortschatz", q: "Was bedeutet „eine Erfahrung machen“?", options: ["etwas erleben und daraus lernen", "etwas bezahlen", "etwas verkaufen", "etwas erklären"], answer: 0 },
  { id: 319, level: "B1", topic: "Wortschatz", q: "Wenn man eine neue Arbeitsstelle sucht, kann man sich bei einer Firma ___.", options: ["anmelden", "bewerben", "bedanken", "entschuldigen"], answer: 1 },
  { id: 320, level: "B1", topic: "Wortschatz", q: "Was bedeutet „zuverlässig“?", options: ["Man kann sich auf eine Person verlassen.", "Eine Person kommt immer zu spät.", "Eine Person spricht sehr leise.", "Eine Person arbeitet nie."], answer: 0 },
  { id: 321, level: "B1", topic: "Satzverbindung", q: "Ich hatte gestern viel zu tun, ___ konnte ich nicht mitkommen.", options: ["trotzdem", "deshalb", "obwohl", "aber"], answer: 1 },
  { id: 322, level: "B1", topic: "Meinung äußern", q: "Du möchtest deine Meinung sagen. Welche Antwort passt?", options: ["Meiner Meinung nach ist Deutsch eine interessante Sprache.", "Wann beginnt der Unterricht?", "Ich war gestern zu Hause.", "Wo ist die nächste Apotheke?"], answer: 0 },
  { id: 323, level: "B1", topic: "Vorschlag", q: "Du möchtest mit deinen Freunden etwas unternehmen. Was passt?", options: ["Wie wäre es, wenn wir am Samstag ins Kino gehen?", "Ich bin gestern ins Kino gegangen.", "Der Film beginnt um acht Uhr.", "Ich mag diesen Schauspieler."], answer: 0 },
  { id: 324, level: "B1", topic: "Höflich widersprechen", q: "Dein Freund sagt: „Deutsch ist sehr einfach.“ Du bist anderer Meinung. Was kannst du sagen?", options: ["Das stimmt genau.", "Da bin ich nicht ganz deiner Meinung.", "Natürlich hast du recht.", "Das sehe ich genauso."], answer: 1 },
  { id: 325, level: "B1", topic: "Grund nennen", q: "„Warum lernst du Deutsch?“ — Was passt?", options: ["Deshalb lerne ich Deutsch.", "Trotzdem lerne ich Deutsch.", "Weil ich später in Deutschland studieren möchte.", "Obwohl ich Deutsch lerne."], answer: 2 },
  { id: 326, level: "B1", topic: "Konnektor „trotzdem“", q: "Es regnet, ___ gehe ich spazieren.", options: ["weil", "obwohl", "trotzdem", "deshalb"], answer: 2 },
  { id: 327, level: "B1", topic: "Passiv", q: "Das Essen ___ jeden Tag frisch gekocht.", options: ["wird", "werden", "hat", "ist"], answer: 0 },
  { id: 328, level: "B1", topic: "Indirekte Frage", q: "Ich weiß nicht, ___ er heute kommt.", options: ["ob", "dass", "weil", "trotzdem"], answer: 0 },
  { id: 329, level: "B1", topic: "Wortschatz", q: "Was bedeutet „pünktlich“?", options: ["zu spät", "genau zur richtigen Zeit", "sehr schnell", "sehr langsam"], answer: 1 },
  { id: 330, level: "B1", topic: "Wortschatz", q: "Wenn man eine Wohnung sucht, kann man eine ___ lesen.", options: ["Anzeige", "Prüfung", "Rechnung", "Einladung"], answer: 0 },
  { id: 331, level: "B1", topic: "Reflexives Verb", q: "Wir ___ auf die Prüfung.", options: ["bereiten uns vor", "uns vorbereiten", "bereiten vor uns", "vorbereitet uns"], answer: 0 },
  { id: 332, level: "B1", topic: "Konjunktiv II", q: "Wenn ich mehr Zeit hätte, ___ ich mehr Sport machen.", options: ["werde", "würde", "wurde", "bin"], answer: 1 },
  { id: 333, level: "B1", topic: "Relativsatz", q: "Das ist die Stadt, ___ ich sehr gern besuche.", options: ["der", "die", "dem", "den"], answer: 1 },
  { id: 334, level: "B1", topic: "Passiv", q: "In Deutschland ___ viele Autos produziert.", options: ["wird", "werden", "hat", "ist"], answer: 1 },
  { id: 335, level: "B1", topic: "Wortschatz", q: "Was bedeutet „sich bewerben“?", options: ["einen Urlaub machen", "eine Stelle suchen und dafür Unterlagen schicken", "eine Wohnung mieten", "eine Prüfung machen"], answer: 1 },
  { id: 336, level: "B1", topic: "Indirekte Frage", q: "Welche Frage ist richtig?", options: ["Weißt du, wann der Kurs beginnt?", "Weißt du, wann beginnt der Kurs?", "Weißt du, wann der Kurs beginnt er?", "Weißt du, der Kurs wann beginnt?"], answer: 0 },
  { id: 337, level: "B1", topic: "Satzstellung", q: "Ergänze: Obwohl ich müde bin, ___.", options: ["ich gehe ins Fitnessstudio", "gehe ich ins Fitnessstudio", "ich ins Fitnessstudio gehe", "ins Fitnessstudio ich gehe"], answer: 1 },
  { id: 338, level: "B1", topic: "Meinung äußern", q: "Du möchtest deine Meinung sagen. Was passt?", options: ["Ich denke, dass das eine gute Idee ist.", "Ich habe gestern gearbeitet.", "Wo ist der Bahnhof?", "Ich möchte einen Kaffee."], answer: 0 },
  { id: 339, level: "B1", topic: "Höflich widersprechen", q: "Du bist mit einer Meinung nicht einverstanden. Was passt?", options: ["Genau, das sehe ich auch so.", "Da bin ich anderer Meinung.", "Das finde ich auch.", "Das stimmt genau."], answer: 1 },
  { id: 340, level: "B1", topic: "Konjunktiv II", q: "Wenn ich Zeit ___, würde ich mehr lesen.", options: ["habe", "hatte", "hätte", "haben"], answer: 2 },
  { id: 341, level: "B1", topic: "Relativsatz", q: "Das Haus, ___ wir gekauft haben, ist alt.", options: ["den", "das", "dem", "der"], answer: 1 },
  { id: 342, level: "B1", topic: "Passiv Präteritum", q: "Der Brief ___ gestern geschrieben.", options: ["wird", "ist", "hat", "wurde"], answer: 3 },
  { id: 343, level: "B1", topic: "Konnektor „um … zu“", q: "Ich lerne Deutsch, ___ in Deutschland zu studieren.", options: ["für", "damit", "um", "weil"], answer: 2 },
  { id: 344, level: "B1", topic: "Infinitiv mit „zu“", q: "Ich habe keine Lust, ___ Hausaufgaben zu machen.", options: ["den", "der", "das", "die"], answer: 3 },

  // ───────────────────────────── B2 ─────────────────────────────
  { id: 401, level: "B2", topic: "Konjunktiv II", q: "Wenn ich mehr Geld ___, würde ich eine längere Reise machen.", options: ["habe", "hätte", "hatte", "haben"], answer: 1 },
  { id: 402, level: "B2", topic: "Konjunktiv II", q: "An deiner Stelle ___ ich mit dem Lehrer darüber sprechen.", options: ["werde", "würde", "werde ich", "hätte"], answer: 1 },
  { id: 403, level: "B2", topic: "Plusquamperfekt", q: "Nachdem er die Prüfung ___, ging er nach Hause.", options: ["bestanden hat", "bestanden hatte", "besteht", "bestehen wird"], answer: 1 },
  { id: 404, level: "B2", topic: "Konnektor „während“", q: "___ ich früher mit dem Bus gefahren bin, fahre ich jetzt meistens mit dem Fahrrad.", options: ["Während", "Obwohl", "Deshalb", "Damit"], answer: 0 },
  { id: 405, level: "B2", topic: "Konnektor", q: "Sie hatte keine Zeit, ___ konnte sie nicht an der Besprechung teilnehmen.", options: ["obwohl", "deshalb", "während", "damit"], answer: 1 },
  { id: 406, level: "B2", topic: "Konnektor „obwohl“", q: "___ er sehr gut vorbereitet war, war er vor der Prüfung nervös.", options: ["Weil", "Obwohl", "Deshalb", "Damit"], answer: 1 },
  { id: 407, level: "B2", topic: "Infinitiv mit „zu“", q: "Ich habe vor, nächstes Jahr in Deutschland ___.", options: ["studieren", "zu studieren", "studiert", "studiere"], answer: 1 },
  { id: 408, level: "B2", topic: "Präposition", q: "Viele Studenten leiden ___ Prüfungsstress.", options: ["für", "über", "unter", "an"], answer: 2 },
  { id: 409, level: "B2", topic: "Adjektivdeklination", q: "Wir suchen eine Wohnung mit einem groß___ Balkon.", options: ["-e", "-en", "-em", "-er"], answer: 1 },
  { id: 410, level: "B2", topic: "Relativsatz", q: "Das ist der Kurs, ___ ich dir gestern erzählt habe.", options: ["der", "den", "von dem", "dessen"], answer: 2 },
  { id: 411, level: "B2", topic: "Relativsatz", q: "Die Frau, ___ Sohn in Deutschland studiert, arbeitet bei uns.", options: ["die", "deren", "der", "dessen"], answer: 1 },
  { id: 412, level: "B2", topic: "Passiv", q: "In diesem Gebäude ___ gerade neue Büros eingerichtet.", options: ["werden", "wurden", "haben", "sind"], answer: 0 },
  { id: 413, level: "B2", topic: "Passiv mit Modalverb", q: "Die Bewerbung ___ bis Montag abgeschickt werden.", options: ["muss", "muss abgeschickt", "muss abgeschickt werden", "wird abgeschickt"], answer: 0 },
  { id: 414, level: "B2", topic: "Konnektor „um … zu“", q: "Er lernt jeden Abend Deutsch, ___ die B2-Prüfung erfolgreich zu bestehen.", options: ["damit", "um", "obwohl", "sodass"], answer: 1 },
  { id: 415, level: "B2", topic: "Konnektor „damit“", q: "Ich erkläre dir die Grammatik noch einmal, ___ du sie besser verstehen kannst.", options: ["um", "damit", "obwohl", "während"], answer: 1 },
  { id: 416, level: "B2", topic: "Wortschatz", q: "Was bedeutet „eine Entscheidung treffen“?", options: ["eine Entscheidung vergessen", "eine Entscheidung machen", "sich für etwas entscheiden", "eine Entscheidung erklären"], answer: 2 },
  { id: 417, level: "B2", topic: "Wortschatz", q: "Was bedeutet „eine Aufgabe erledigen“?", options: ["eine Aufgabe beginnen und nicht beenden", "eine Aufgabe erfolgreich fertig machen", "eine Aufgabe vergessen", "eine Aufgabe verschieben"], answer: 1 },
  { id: 418, level: "B2", topic: "Wortschatz", q: "Was bedeutet „sich auf etwas verlassen können“?", options: ["etwas nicht verstehen", "jemandem oder etwas vertrauen können", "etwas vermeiden", "etwas ablehnen"], answer: 1 },
  { id: 419, level: "B2", topic: "Wortschatz", q: "Viele junge Menschen möchten nach der Schule Berufserfahrung ___.", options: ["nehmen", "sammeln", "machen", "bekommen"], answer: 1 },
  { id: 420, level: "B2", topic: "Satzverbindung", q: "Er war krank. ___ ging er zur Arbeit.", options: ["Trotzdem", "Deshalb", "Weil", "Damit"], answer: 0 },
  { id: 421, level: "B2", topic: "Satzbau", q: "Welche Variante ist grammatisch richtig?", options: ["Obwohl er hatte wenig Zeit, half er seinem Freund.", "Obwohl hatte er wenig Zeit, half er seinem Freund.", "Obwohl er wenig Zeit hatte, half er seinem Freund.", "Obwohl wenig Zeit er hatte, er half seinem Freund."], answer: 2 },
  { id: 422, level: "B2", topic: "Meinung äußern", q: "Du möchtest deine Meinung zu einem Thema ausdrücken. Welche Aussage passt am besten?", options: ["Meiner Meinung nach sollte man dieses Problem ernst nehmen.", "Ich habe gestern lange gearbeitet.", "Wann beginnt der Kurs?", "Ich habe keine Zeit gehabt."], answer: 0 },
  { id: 423, level: "B2", topic: "Höflichkeit", q: "Welche Formulierung klingt am höflichsten?", options: ["Das ist völlig falsch!", "Du hast keine Ahnung.", "Ich sehe das etwas anders und möchte einen anderen Aspekt hervorheben.", "Nein, das stimmt überhaupt nicht."], answer: 2 },
  { id: 424, level: "B2", topic: "Vor- und Nachteile", q: "Welche Aussage eignet sich am besten, um Vor- und Nachteile zu vergleichen?", options: ["Ich finde diese Idee interessant.", "Einerseits spart man Zeit, andererseits kann diese Lösung zusätzliche Kosten verursachen.", "Diese Lösung ist sehr interessant.", "Ich habe darüber schon einmal gesprochen."], answer: 1 },
  { id: 425, level: "B2", topic: "Konjunktiv II Vergangenheit", q: "Wenn ich früher losgegangen wäre, ___ ich den Zug erreicht.", options: ["habe", "hätte", "würde", "werde"], answer: 1 },
  { id: 426, level: "B2", topic: "Passiv", q: "Die neuen Wohnungen ___ nächstes Jahr gebaut.", options: ["werden", "wurden", "haben", "sind"], answer: 0 },
  { id: 427, level: "B2", topic: "Relativsatz", q: "Das ist die Kollegin, ___ ich gestern geholfen habe.", options: ["die", "der", "den", "deren"], answer: 1 },
  { id: 428, level: "B2", topic: "Adjektivdeklination", q: "Er hat mit einem sehr freundlich___ Mann gesprochen.", options: ["-e", "-en", "-em", "-er"], answer: 1 },
  { id: 429, level: "B2", topic: "Präposition + Genitiv", q: "___ des schlechten Wetters fand das Konzert statt.", options: ["Obwohl", "Trotz", "Deshalb", "Während"], answer: 1 },
  { id: 430, level: "B2", topic: "Wortschatz", q: "Was bedeutet „eine Lösung finden“?", options: ["ein Problem lösen", "ein Problem vergessen", "ein Problem wiederholen", "ein Problem erklären"], answer: 0 },
  { id: 431, level: "B2", topic: "Wortschatz", q: "„Die Nachfrage nach Wohnungen ist gestiegen.“ Was bedeutet „Nachfrage“?", options: ["Interesse bzw. Bedarf an etwas", "Preis von etwas", "Größe von etwas", "Qualität von etwas"], answer: 0 },
  { id: 432, level: "B2", topic: "Indirekte Rede", q: "Er sagt: „Ich komme morgen.“ → Er sagt, dass er am nächsten Tag ___.", options: ["kommt", "kommen wird", "gekommen ist", "kam"], answer: 0 },
  { id: 433, level: "B2", topic: "Präposition + Genitiv", q: "___ der hohen Kosten haben wir das Projekt abgesagt.", options: ["Wegen", "Trotz", "Mit", "Bei"], answer: 0 },
  { id: 434, level: "B2", topic: "Konzessivsatz", q: "___ er sehr müde war, arbeitete er weiter.", options: ["Obwohl", "Deshalb", "Trotzdem", "Wegen"], answer: 0 },
  { id: 435, level: "B2", topic: "„je … desto“", q: "___ mehr Deutsch man spricht, ___ sicherer wird man.", options: ["Je … desto", "Wenn … dann", "Je … weil", "Obwohl … desto"], answer: 0 },
  { id: 436, level: "B2", topic: "Konnektor „sodass“", q: "Er hat sehr viel gelernt, ___ er die Prüfung bestehen konnte.", options: ["obwohl", "sodass", "während", "trotzdem"], answer: 1 },
  { id: 437, level: "B2", topic: "Präposition", q: "Wir müssen uns ___ die neue Situation gewöhnen.", options: ["an", "auf", "über", "mit"], answer: 0 },
  { id: 438, level: "B2", topic: "Satzstruktur", q: "Welche Satzstruktur ist richtig?", options: ["Obwohl die Arbeit schwierig war, konnte er sie erfolgreich beenden.", "Obwohl die Arbeit war schwierig, konnte er sie erfolgreich beenden.", "Obwohl die Arbeit schwierig war, er konnte sie erfolgreich beenden.", "Obwohl schwierig die Arbeit war, konnte er sie beenden."], answer: 0 },
  { id: 439, level: "B2", topic: "„je … desto“", q: "Welche Variante ist richtig?", options: ["Je länger man wartet, desto schwieriger wird die Situation.", "Je länger man wartet, desto die Situation schwieriger wird.", "Je länger wartet man, desto schwieriger die Situation wird.", "Je länger man wartet, desto wird die Situation schwieriger."], answer: 0 },
  { id: 440, level: "B2", topic: "Genitiv", q: "Welche Variante ist richtig?", options: ["Aufgrund des starken Regens wurde das Spiel abgesagt.", "Aufgrund den starken Regen wurde das Spiel abgesagt.", "Aufgrund der starken Regen wurde das Spiel abgesagt.", "Aufgrund starkem Regen wurde das Spiel abgesagt."], answer: 0 },
  { id: 441, level: "B2", topic: "Plusquamperfekt", q: "Welche Variante ist richtig?", options: ["Er hat die Prüfung bestanden, obwohl er nur wenig gelernt hatte.", "Er hat die Prüfung bestanden, obwohl hatte er nur wenig gelernt.", "Er hat die Prüfung bestanden, obwohl er hatte nur wenig gelernt.", "Er hat die Prüfung bestanden, obwohl nur wenig er gelernt hatte."], answer: 0 },
  { id: 442, level: "B2", topic: "Meinung äußern", q: "Du möchtest deine Meinung ausdrücken. Was passt?", options: ["Meiner Ansicht nach hat diese Lösung mehr Vorteile als Nachteile.", "Ich habe gestern gearbeitet.", "Wo befindet sich der Bahnhof?", "Ich möchte einen Kaffee bestellen."], answer: 0 },
  { id: 443, level: "B2", topic: "Höflich widersprechen", q: "Du möchtest höflich widersprechen. Was passt?", options: ["Das ist absolut falsch!", "Ich sehe das etwas anders, weil es auch andere Möglichkeiten gibt.", "Nein, das stimmt nicht!", "Du hast keine Ahnung."], answer: 1 },
  { id: 444, level: "B2", topic: "Vorschlag", q: "Du möchtest einen Vorschlag machen. Was passt?", options: ["Ich würde vorschlagen, dass wir zunächst beide Möglichkeiten vergleichen.", "Ich habe gestern darüber gesprochen.", "Das ist schon lange bekannt.", "Ich kenne diese Möglichkeit."], answer: 0 },
  { id: 445, level: "B2", topic: "Konnektor „nachdem“", q: "___ er viel gearbeitet hatte, war er müde.", options: ["Bevor", "Während", "Nachdem", "Obwohl"], answer: 2 },
  { id: 446, level: "B2", topic: "Passiv mit Modalverb", q: "Die Ergebnisse ___ noch überprüft werden.", options: ["muss", "müssen", "gemusst", "müsste"], answer: 1 },
  { id: 447, level: "B2", topic: "„als ob“", q: "Er tat so, ___ er nichts wüsste.", options: ["obwohl", "wenn", "als ob", "als"], answer: 2 },
  { id: 448, level: "B2", topic: "Relativsatz mit Präposition", q: "Die Stadt, in ___ ich wohne, ist sehr alt.", options: ["die", "dem", "der", "den"], answer: 2 },
];
