// Daraja aniqlash testi — SAVOLLAR BANKI (to'plamlar bo'yicha).
//
// Manba: markazning o'z test to'plamlari (2026-09): har daraja ichida ikki
// test — A1.1 / A1.2, A2.1 / A2.2, B1.1 / B1.2, B2.1 / B2.2, har biri 25 ta
// savol (B2.2 — 24). Savollar to'plamdagi ASL TARTIBDA, aralashtirilmaydi:
// mijoz darajani va testni o'zi tanlaydi, aynan shu to'plamni topshiradi.
//
// To'plamlarda javob kaliti yo'q edi — `answer` grammatika bo'yicha
// belgilangan. A2.1 №9 ("Ich fahre morgen ___ Berlin" — variantlarda "nach"
// yo'q edi) tuzatilgan. Bu fayl faqat serverda o'qiladi — `answer` mijozga
// bormaydi.
//
// id: to'plam × 100 + tartib raqami (A1.1 → 11xx, A1.2 → 12xx, A2.1 → 21xx ...).

import type { LevelTestQuestion } from "./levelTest";

export const LEVEL_TEST_BANK: LevelTestQuestion[] = [
  // ═══════════════════════════ A1.1 ═══════════════════════════
  { id: 1101, set: "A1.1", level: "A1", topic: "Begrüßung", q: "Du kommst am Morgen in die Schule. Was sagst du?", options: ["Gute Nacht!", "Guten Morgen!", "Gute Reise!", "Guten Appetit!"], answer: 1 },
  { id: 1102, set: "A1.1", level: "A1", topic: "Personalpronomen", q: "___ heiße Anna.", options: ["Ich", "Du", "Er", "Sie"], answer: 0 },
  { id: 1103, set: "A1.1", level: "A1", topic: "Verb „sein“", q: "Ich ___ Maria.", options: ["bist", "ist", "bin", "sind"], answer: 2 },
  { id: 1104, set: "A1.1", level: "A1", topic: "Verb „sein“", q: "Du ___ Student.", options: ["bin", "bist", "ist", "sind"], answer: 1 },
  { id: 1105, set: "A1.1", level: "A1", topic: "Verb „haben“", q: "Ich ___ ein Handy.", options: ["bist", "habe", "hat", "haben"], answer: 1 },
  { id: 1106, set: "A1.1", level: "A1", topic: "Artikel", q: "___ Mann ist nett.", options: ["Die", "Das", "Der", "Eine"], answer: 2 },
  { id: 1107, set: "A1.1", level: "A1", topic: "Artikel", q: "___ Frau heißt Anna.", options: ["Der", "Die", "Das", "Ein"], answer: 1 },
  { id: 1108, set: "A1.1", level: "A1", topic: "Wortschatz", q: "Was ist das? 🥛", options: ["das Wasser", "die Milch", "der Kaffee", "der Saft"], answer: 1 },
  { id: 1109, set: "A1.1", level: "A1", topic: "Zahlen", q: "Wie viel ist „zehn“?", options: ["5", "10", "15", "20"], answer: 1 },
  { id: 1110, set: "A1.1", level: "A1", topic: "Farben", q: "Welche Farbe hat eine Banane normalerweise?", options: ["blau", "schwarz", "gelb", "weiß"], answer: 2 },
  { id: 1111, set: "A1.1", level: "A1", topic: "Präsens", q: "Ich ___ Deutsch.", options: ["lerne", "lernst", "lernt", "lernen"], answer: 0 },
  { id: 1112, set: "A1.1", level: "A1", topic: "Präsens", q: "Er ___ in Berlin.", options: ["wohnen", "wohnst", "wohnt", "wohne"], answer: 2 },
  { id: 1113, set: "A1.1", level: "A1", topic: "Präsens", q: "Wir ___ in Taschkent.", options: ["wohnt", "wohnen", "wohnst", "wohne"], answer: 1 },
  { id: 1114, set: "A1.1", level: "A1", topic: "Personalpronomen", q: "Anna ist meine Freundin. ___ ist sehr nett.", options: ["Er", "Es", "Sie", "Wir"], answer: 2 },
  { id: 1115, set: "A1.1", level: "A1", topic: "Negation mit „nicht“", q: "Ich bin ___ müde.", options: ["kein", "keine", "nicht", "nein"], answer: 2 },
  { id: 1116, set: "A1.1", level: "A1", topic: "Negation mit „kein“", q: "Ich habe ___ Auto.", options: ["nicht", "kein", "keine", "nein"], answer: 1 },
  { id: 1117, set: "A1.1", level: "A1", topic: "Possessivartikel", q: "Das ist ___ Buch.", options: ["ich", "mein", "meine", "mich"], answer: 1 },
  { id: 1118, set: "A1.1", level: "A1", topic: "Akkusativ", q: "Ich habe ___ Bruder.", options: ["ein", "einen", "eine", "einem"], answer: 1 },
  { id: 1119, set: "A1.1", level: "A1", topic: "Modalverb", q: "Ich ___ Deutsch sprechen.", options: ["kann", "kannst", "können", "gekannt"], answer: 0 },
  { id: 1120, set: "A1.1", level: "A1", topic: "Satzstruktur", q: "Welche Variante ist richtig?", options: ["Ich Deutsch lerne.", "Deutsch ich lerne.", "Ich lerne Deutsch.", "Lerne Deutsch ich."], answer: 2 },
  { id: 1121, set: "A1.1", level: "A1", topic: "Frage", q: "Welche Frage ist richtig?", options: ["Wie heißt du?", "Wie du heißt?", "Wie heißen du?", "Heißt wie du?"], answer: 0 },
  { id: 1122, set: "A1.1", level: "A1", topic: "Woher kommen?", q: "„Woher kommst du?“ — Was passt?", options: ["Ich bin 20 Jahre alt.", "Ich komme aus Usbekistan.", "Ich wohne in Berlin.", "Ich heiße Anna."], answer: 1 },
  { id: 1123, set: "A1.1", level: "A1", topic: "Wie geht es dir?", q: "Jemand fragt: „Wie geht es dir?“ — Was passt?", options: ["Ich komme aus Usbekistan.", "Ich bin Student.", "Danke, sehr gut.", "Ich bin 20 Jahre alt."], answer: 2 },
  { id: 1124, set: "A1.1", level: "A1", topic: "Im Café", q: "Du möchtest einen Kaffee bestellen. Was sagst du?", options: ["Ich heiße Ali.", "Ich möchte einen Kaffee, bitte.", "Woher kommst du?", "Wie alt bist du?"], answer: 1 },
  { id: 1125, set: "A1.1", level: "A1", topic: "Sich verabschieden", q: "Du gehst nach Hause. Was kannst du sagen?", options: ["Guten Morgen!", "Guten Appetit!", "Auf Wiedersehen!", "Danke schön!"], answer: 2 },

  // ═══════════════════════════ A1.2 ═══════════════════════════
  { id: 1201, set: "A1.2", level: "A1", topic: "Artikel", q: "___ Tisch ist groß.", options: ["Die", "Der", "Das", "Eine"], answer: 1 },
  { id: 1202, set: "A1.2", level: "A1", topic: "sein / haben", q: "Ich ___ Studentin.", options: ["habe", "bist", "bin", "ist"], answer: 2 },
  { id: 1203, set: "A1.2", level: "A1", topic: "sein / haben", q: "Wir ___ ein Haus.", options: ["sind", "haben", "hat", "seid"], answer: 1 },
  { id: 1204, set: "A1.2", level: "A1", topic: "Präsens", q: "Anna ___ in Berlin.", options: ["wohnen", "wohnst", "wohnt", "wohne"], answer: 2 },
  { id: 1205, set: "A1.2", level: "A1", topic: "Wortschatz", q: "Was ist das? 🍎", options: ["die Banane", "der Apfel", "die Orange", "das Brot"], answer: 1 },
  { id: 1206, set: "A1.2", level: "A1", topic: "Zahlen", q: "Wie viel ist „zwanzig“?", options: ["12", "20", "30", "22"], answer: 1 },
  { id: 1207, set: "A1.2", level: "A1", topic: "Wochentage", q: "Welcher Tag kommt nach Montag?", options: ["Sonntag", "Freitag", "Dienstag", "Mittwoch"], answer: 2 },
  { id: 1208, set: "A1.2", level: "A1", topic: "Uhrzeit", q: "08:00 Uhr — Wie sagt man das?", options: ["Es ist acht Uhr.", "Es ist achtzehn Uhr.", "Es ist sieben Uhr.", "Es ist neun Uhr."], answer: 0 },
  { id: 1209, set: "A1.2", level: "A1", topic: "Artikel", q: "Ich habe ___ Tasche.", options: ["ein", "eine", "einen", "der"], answer: 1 },
  { id: 1210, set: "A1.2", level: "A1", topic: "Negation", q: "Ich habe ___ Auto.", options: ["nicht", "kein", "keine", "nein"], answer: 1 },
  { id: 1211, set: "A1.2", level: "A1", topic: "Negation", q: "Das ist ___ mein Buch.", options: ["kein", "nicht", "keine", "nein"], answer: 1 },
  { id: 1212, set: "A1.2", level: "A1", topic: "Plural", q: "Das ist ein Kind. → Das sind zwei ___.", options: ["Kinds", "Kinder", "Kinders", "Kind"], answer: 1 },
  { id: 1213, set: "A1.2", level: "A1", topic: "Possessivartikel", q: "Das ist ___ Mutter.", options: ["ich", "mein", "meine", "mich"], answer: 2 },
  { id: 1214, set: "A1.2", level: "A1", topic: "Präsens", q: "Wir ___ jeden Morgen Kaffee.", options: ["trinken", "trinkt", "trinkst", "getrunken"], answer: 0 },
  { id: 1215, set: "A1.2", level: "A1", topic: "Modalverb", q: "Ich ___ Deutsch lernen.", options: ["kann", "können", "kannst", "gekannt"], answer: 0 },
  { id: 1216, set: "A1.2", level: "A1", topic: "Wortschatz", q: "Was macht man in einem Supermarkt?", options: ["Man kauft ein.", "Man schläft.", "Man arbeitet im Krankenhaus.", "Man schwimmt."], answer: 0 },
  { id: 1217, set: "A1.2", level: "A1", topic: "Präposition", q: "Ich komme ___ Deutschland.", options: ["mit", "aus", "bei", "an"], answer: 1 },
  { id: 1218, set: "A1.2", level: "A1", topic: "Satzstruktur", q: "Welche Satzstruktur ist richtig?", options: ["Ich jeden Tag Deutsch lerne.", "Deutsch ich lerne jeden Tag.", "Ich lerne jeden Tag Deutsch.", "Jeden ich Tag Deutsch lerne."], answer: 2 },
  { id: 1219, set: "A1.2", level: "A1", topic: "Frage", q: "Welche Frage ist richtig?", options: ["Wo du wohnst?", "Wo wohnst du?", "Wo du wohnen?", "Wohnst wo du?"], answer: 1 },
  { id: 1220, set: "A1.2", level: "A1", topic: "Ja-/Nein-Frage", q: "___ du aus Usbekistan?", options: ["Bist", "Ist", "Sind", "Sein"], answer: 0 },
  { id: 1221, set: "A1.2", level: "A1", topic: "Satz ergänzen", q: "Am Montag ___ ich Deutsch.", options: ["lernen", "lernst", "lerne", "lernt"], answer: 2 },
  { id: 1222, set: "A1.2", level: "A1", topic: "Kennenlernen", q: "Du möchtest jemanden kennenlernen. Was sagst du?", options: ["Wie heißen Sie?", "Guten Appetit!", "Gute Nacht!", "Gute Reise!"], answer: 0 },
  { id: 1223, set: "A1.2", level: "A1", topic: "Wie geht es dir?", q: "Jemand fragt: „Wie geht es dir?“ Was passt?", options: ["Ich bin 20 Jahre alt.", "Danke, sehr gut.", "Ich komme aus Samarkand.", "Ich habe einen Bruder."], answer: 1 },
  { id: 1224, set: "A1.2", level: "A1", topic: "Im Café", q: "Du möchtest etwas im Café bestellen. Was sagst du?", options: ["Ich möchte einen Kaffee, bitte.", "Wo wohnst du?", "Wie alt bist du?", "Was machst du beruflich?"], answer: 0 },
  { id: 1225, set: "A1.2", level: "A1", topic: "Dialog", q: "Jemand sagt: „Danke!“ Was antwortest du?", options: ["Guten Morgen!", "Bitte!", "Entschuldigung!", "Gute Nacht!"], answer: 1 },

  // ═══════════════════════════ A2.1 ═══════════════════════════
  { id: 2101, set: "A2.1", level: "A2", topic: "Perfekt", q: "Ich ___ gestern einen Kaffee ___.", options: ["habe … getrunken", "bin … getrunken", "habe … trinken", "bin … trinken"], answer: 0 },
  { id: 2102, set: "A2.1", level: "A2", topic: "Perfekt", q: "Wir ___ am Wochenende einen Film ___.", options: ["sind … gesehen", "haben … gesehen", "haben … sehen", "sind … sehen"], answer: 1 },
  { id: 2103, set: "A2.1", level: "A2", topic: "Modalverb", q: "Ich ___ heute leider nicht kommen.", options: ["kann", "kannst", "können", "gekonnt"], answer: 0 },
  { id: 2104, set: "A2.1", level: "A2", topic: "Akkusativ", q: "Ich kaufe ___ neuen Computer.", options: ["ein", "einen", "einem", "einer"], answer: 1 },
  { id: 2105, set: "A2.1", level: "A2", topic: "Dativ", q: "Ich helfe ___ Freund bei den Hausaufgaben.", options: ["mein", "meinen", "meinem", "meiner"], answer: 2 },
  { id: 2106, set: "A2.1", level: "A2", topic: "Possessivartikel", q: "Das ist ___ Schwester.", options: ["mein", "meine", "meinen", "meinem"], answer: 1 },
  { id: 2107, set: "A2.1", level: "A2", topic: "Trennbare Verben", q: "Ich ___ jeden Morgen um 7 Uhr ___.", options: ["stehe … auf", "aufstehe … —", "stehe auf … —", "auf … stehe"], answer: 0 },
  { id: 2108, set: "A2.1", level: "A2", topic: "Reflexives Verb", q: "Ich ___ jeden Morgen.", options: ["dusche mich", "mich dusche", "dusche mir", "mich duschen"], answer: 0 },
  { id: 2109, set: "A2.1", level: "A2", topic: "Präposition", q: "Ich fahre morgen ___ Berlin.", options: ["nach", "in", "an", "bei"], answer: 0 },
  { id: 2110, set: "A2.1", level: "A2", topic: "Präposition", q: "Am Wochenende treffe ich mich ___ meiner Freundin.", options: ["für", "mit", "ohne", "durch"], answer: 1 },
  { id: 2111, set: "A2.1", level: "A2", topic: "Konnektor „weil“", q: "Ich bleibe zu Hause, ___ ich krank bin.", options: ["aber", "oder", "weil", "und"], answer: 2 },
  { id: 2112, set: "A2.1", level: "A2", topic: "Satzstellung mit „weil“", q: "Welche Variante ist richtig?", options: ["Weil ich krank bin, bleibe ich zu Hause.", "Weil ich bin krank, bleibe ich zu Hause.", "Weil krank ich bin, ich bleibe zu Hause.", "Weil ich krank bin, ich zu Hause bleibe."], answer: 0 },
  { id: 2113, set: "A2.1", level: "A2", topic: "„dass“", q: "Ich glaube, ___ er heute keine Zeit hat.", options: ["weil", "dass", "wenn", "aber"], answer: 1 },
  { id: 2114, set: "A2.1", level: "A2", topic: "Temporalsatz mit „wenn“", q: "___ ich frei habe, gehe ich gern spazieren.", options: ["Weil", "Dass", "Wenn", "Aber"], answer: 2 },
  { id: 2115, set: "A2.1", level: "A2", topic: "Präteritum von „sein“", q: "Gestern ___ das Wetter sehr schön.", options: ["ist", "war", "hatte", "ist gewesen"], answer: 1 },
  { id: 2116, set: "A2.1", level: "A2", topic: "Präteritum von „haben“", q: "Früher ___ ich ein kleines Fahrrad.", options: ["habe", "bin", "hatte", "war"], answer: 2 },
  { id: 2117, set: "A2.1", level: "A2", topic: "Vergleich", q: "Meine Schwester ist ___ als ich.", options: ["groß", "größer", "am größten", "mehr groß"], answer: 1 },
  { id: 2118, set: "A2.1", level: "A2", topic: "Wortschatz", q: "Was bedeutet „mieten“?", options: ["etwas kaufen", "etwas für eine bestimmte Zeit gegen Geld benutzen", "etwas verkaufen", "etwas reparieren"], answer: 1 },
  { id: 2119, set: "A2.1", level: "A2", topic: "Wortschatz", q: "Was bedeutet „abholen“?", options: ["jemanden oder etwas an einem Ort holen", "etwas bezahlen", "etwas vergessen", "etwas erklären"], answer: 0 },
  { id: 2120, set: "A2.1", level: "A2", topic: "Satzstruktur", q: "Welche Satzstruktur ist richtig?", options: ["Ich habe gestern meine Hausaufgaben gemacht.", "Ich gestern habe meine Hausaufgaben gemacht.", "Ich habe gemacht gestern meine Hausaufgaben.", "Gestern ich habe meine Hausaufgaben gemacht."], answer: 0 },
  { id: 2121, set: "A2.1", level: "A2", topic: "Satz ergänzen", q: "Ich kann heute nicht kommen, ___ ich arbeiten muss.", options: ["aber", "weil", "und", "oder"], answer: 1 },
  { id: 2122, set: "A2.1", level: "A2", topic: "Um Hilfe bitten", q: "Du möchtest jemanden um Hilfe bitten. Was passt?", options: ["Kannst du mir bitte helfen?", "Du hilfst mir!", "Ich helfe dir gestern.", "Du musst gestern helfen."], answer: 0 },
  { id: 2123, set: "A2.1", level: "A2", topic: "Termin vereinbaren", q: "Du möchtest einen Termin vereinbaren. Was sagst du?", options: ["Wann hast du gestern gearbeitet?", "Ich möchte gern einen Termin vereinbaren.", "Ich habe keinen Termin gehabt.", "Der Termin war gestern."], answer: 1 },
  { id: 2124, set: "A2.1", level: "A2", topic: "Dialog", q: "Jemand fragt: „Was hast du gestern gemacht?“", options: ["Ich gehe morgen einkaufen.", "Ich möchte morgen einkaufen gehen.", "Ich habe gestern eingekauft.", "Ich kaufe gerade ein."], answer: 2 },
  { id: 2125, set: "A2.1", level: "A2", topic: "Meinung", q: "Du möchtest deine Meinung einfach ausdrücken. Was passt?", options: ["Ich finde diese Idee gut.", "Obwohl diese Idee gut ist.", "Deshalb diese Idee gut.", "Wenn diese Idee gut."], answer: 0 },

  // ═══════════════════════════ A2.2 ═══════════════════════════
  { id: 2201, set: "A2.2", level: "A2", topic: "Perfekt", q: "Ich ___ gestern einen Film ___.", options: ["habe … gesehen", "bin … gesehen", "habe … sehen", "habe … sieht"], answer: 0 },
  { id: 2202, set: "A2.2", level: "A2", topic: "Perfekt mit „sein“", q: "Wir ___ gestern nach Berlin ___.", options: ["haben … gefahren", "sind … gefahren", "sind … fahren", "haben … fahren"], answer: 1 },
  { id: 2203, set: "A2.2", level: "A2", topic: "Modalverb im Präteritum", q: "Als Kind ___ ich viel spielen.", options: ["kann", "konnte", "gekonnt", "können"], answer: 1 },
  { id: 2204, set: "A2.2", level: "A2", topic: "Dativ", q: "Ich helfe ___ Mutter.", options: ["meine", "meiner", "meinen", "mein"], answer: 1 },
  { id: 2205, set: "A2.2", level: "A2", topic: "Akkusativ oder Dativ", q: "Ich gebe ___ Kind einen Ball.", options: ["der", "den", "dem", "das"], answer: 2 },
  { id: 2206, set: "A2.2", level: "A2", topic: "Reflexive Verben", q: "Ich ___ jeden Morgen.", options: ["wasche mich", "mich wasche", "wasche mir", "mich waschen"], answer: 0 },
  { id: 2207, set: "A2.2", level: "A2", topic: "Vergleich", q: "Mein Bruder ist ___ als ich.", options: ["groß", "größer", "am größten", "mehr groß"], answer: 1 },
  { id: 2208, set: "A2.2", level: "A2", topic: "Wortschatz", q: "Was bedeutet „besichtigen“?", options: ["etwas anschauen", "etwas kaufen", "etwas verkaufen", "etwas vergessen"], answer: 0 },
  { id: 2209, set: "A2.2", level: "A2", topic: "Nebensatz mit „weil“", q: "Ich bleibe heute zu Hause, ___ ich krank bin.", options: ["aber", "weil", "deshalb", "oder"], answer: 1 },
  { id: 2210, set: "A2.2", level: "A2", topic: "Satzstruktur", q: "Weil ich morgen arbeiten muss, ___ ich heute zu Hause.", options: ["bleibe", "ich bleibe", "bleibe ich", "ich bleiben"], answer: 0 },
  { id: 2211, set: "A2.2", level: "A2", topic: "„dass“", q: "Ich glaube, ___ er heute keine Zeit hat.", options: ["weil", "dass", "wenn", "aber"], answer: 1 },
  { id: 2212, set: "A2.2", level: "A2", topic: "Temporalsatz mit „wenn“", q: "___ ich Zeit habe, besuche ich meine Freundin.", options: ["Wenn", "Weil", "Dass", "Deshalb"], answer: 0 },
  { id: 2213, set: "A2.2", level: "A2", topic: "Präteritum von „sein“", q: "Gestern ___ ich sehr müde.", options: ["bin", "war", "habe", "hatte"], answer: 1 },
  { id: 2214, set: "A2.2", level: "A2", topic: "Präteritum von „haben“", q: "Früher ___ ich kein Auto.", options: ["bin", "war", "hatte", "habe"], answer: 2 },
  { id: 2215, set: "A2.2", level: "A2", topic: "Präposition", q: "Ich fahre morgen ___ meiner Freundin nach Hamburg.", options: ["mit", "für", "ohne", "durch"], answer: 0 },
  { id: 2216, set: "A2.2", level: "A2", topic: "Adjektiv", q: "Das Wetter ist heute sehr ___.", options: ["schön", "schöne", "schöner", "schönes"], answer: 0 },
  { id: 2217, set: "A2.2", level: "A2", topic: "Wortschatz", q: "Wenn man krank ist, geht man normalerweise zum ___.", options: ["Bäcker", "Arzt", "Bahnhof", "Supermarkt"], answer: 1 },
  { id: 2218, set: "A2.2", level: "A2", topic: "Satzstruktur", q: "Welche Satzstruktur ist richtig?", options: ["Ich habe gestern meine Freundin getroffen.", "Ich gestern habe meine Freundin getroffen.", "Ich habe getroffen gestern meine Freundin.", "Gestern ich meine Freundin habe getroffen."], answer: 0 },
  { id: 2219, set: "A2.2", level: "A2", topic: "Dialog", q: "„Warum lernst du Deutsch?“ — Welche Antwort passt?", options: ["Weil ich in Deutschland arbeiten möchte.", "Wenn ich in Deutschland arbeiten möchte.", "Dass ich in Deutschland arbeiten möchte.", "Deshalb ich in Deutschland arbeiten möchte."], answer: 0 },
  { id: 2220, set: "A2.2", level: "A2", topic: "„obwohl“", q: "Welche Variante ist richtig?", options: ["Obwohl es regnet, gehe ich spazieren.", "Obwohl es regnet, ich gehe spazieren.", "Obwohl regnet es, gehe ich spazieren.", "Obwohl es regnet, ich spazieren gehe."], answer: 0 },
  { id: 2221, set: "A2.2", level: "A2", topic: "Satz ergänzen", q: "Ich habe keine Zeit, ___ ich heute viel arbeiten muss.", options: ["aber", "denn", "weil", "trotzdem"], answer: 2 },
  { id: 2222, set: "A2.2", level: "A2", topic: "Termin vereinbaren", q: "Du möchtest einen Termin vereinbaren. Was sagst du?", options: ["Ich möchte gern einen Termin vereinbaren.", "Ich möchte einen Kaffee trinken.", "Wie viel kostet das?", "Woher kommst du?"], answer: 0 },
  { id: 2223, set: "A2.2", level: "A2", topic: "Höflich bitten", q: "Du möchtest höflich um etwas bitten. Was passt?", options: ["Gib mir das!", "Ich hätte gern ein Glas Wasser, bitte.", "Du musst mir das geben.", "Ich nehme das sofort!"], answer: 1 },
  { id: 2224, set: "A2.2", level: "A2", topic: "Dialog", q: "Jemand fragt: „Was hast du am Wochenende gemacht?“", options: ["Ich habe meine Freunde getroffen.", "Ich treffe meine Freunde morgen.", "Ich werde meine Freunde treffen.", "Ich möchte meine Freunde treffen."], answer: 0 },
  { id: 2225, set: "A2.2", level: "A2", topic: "Meinung", q: "Du bist mit einem Vorschlag nicht einverstanden. Was passt am besten?", options: ["Das finde ich eine gute Idee.", "Ja, natürlich.", "Ich glaube, das ist keine gute Idee.", "Das möchte ich sehr gern."], answer: 2 },

  // ═══════════════════════════ B1.1 ═══════════════════════════
  { id: 3101, set: "B1.1", level: "B1", topic: "Perfekt", q: "Gestern ___ ich meine Freunde getroffen.", options: ["habe", "bin", "werde", "hatte"], answer: 0 },
  { id: 3102, set: "B1.1", level: "B1", topic: "Präteritum", q: "Früher ___ ich jeden Tag mit dem Bus zur Schule.", options: ["fahre", "fuhr", "gefahren", "fahre ich"], answer: 1 },
  { id: 3103, set: "B1.1", level: "B1", topic: "Konnektor „weil“", q: "Ich lerne Deutsch, ___ ich in Deutschland arbeiten möchte.", options: ["aber", "weil", "trotzdem", "deshalb"], answer: 1 },
  { id: 3104, set: "B1.1", level: "B1", topic: "Konnektor „deshalb“", q: "Ich bin heute krank. ___ bleibe ich zu Hause.", options: ["Obwohl", "Weil", "Deshalb", "Aber"], answer: 2 },
  { id: 3105, set: "B1.1", level: "B1", topic: "Modalverb im Präteritum", q: "Als Kind ___ ich nicht lange draußen bleiben.", options: ["kann", "konnte", "gekonnt", "könnte"], answer: 1 },
  { id: 3106, set: "B1.1", level: "B1", topic: "Reflexives Verb", q: "Ich ___ jeden Morgen auf die Arbeit.", options: ["bereite mich vor", "mich bereite vor", "bereite vor mich", "vor mich bereite"], answer: 0 },
  { id: 3107, set: "B1.1", level: "B1", topic: "Präposition", q: "Ich interessiere mich sehr ___ Sport.", options: ["an", "für", "mit", "bei"], answer: 1 },
  { id: 3108, set: "B1.1", level: "B1", topic: "Präposition", q: "Wir warten schon seit einer Stunde ___ den Bus.", options: ["auf", "an", "für", "mit"], answer: 0 },
  { id: 3109, set: "B1.1", level: "B1", topic: "Relativsatz", q: "Das ist der Mann, ___ neben mir wohnt.", options: ["den", "dem", "der", "das"], answer: 2 },
  { id: 3110, set: "B1.1", level: "B1", topic: "Relativsatz", q: "Das ist das Buch, ___ ich gestern gekauft habe.", options: ["der", "die", "das", "dem"], answer: 2 },
  { id: 3111, set: "B1.1", level: "B1", topic: "Konjunktiv II — Wunsch", q: "Ich ___ gern mehr Deutsch sprechen.", options: ["würde", "werde", "wurde", "bin"], answer: 0 },
  { id: 3112, set: "B1.1", level: "B1", topic: "Konjunktiv II — höfliche Bitte", q: "___ Sie mir bitte helfen?", options: ["Werden", "Würden", "Wurden", "Haben"], answer: 1 },
  { id: 3113, set: "B1.1", level: "B1", topic: "„wenn“", q: "___ ich Zeit habe, besuche ich meine Großeltern.", options: ["Obwohl", "Wenn", "Deshalb", "Trotzdem"], answer: 1 },
  { id: 3114, set: "B1.1", level: "B1", topic: "Satzstellung", q: "Welche Variante ist richtig?", options: ["Weil ich heute arbeiten muss, kann ich nicht kommen.", "Weil ich muss heute arbeiten, kann ich nicht kommen.", "Weil heute ich arbeiten muss, kann ich nicht kommen.", "Weil ich heute arbeiten muss, ich kann nicht kommen."], answer: 0 },
  { id: 3115, set: "B1.1", level: "B1", topic: "„obwohl“", q: "___ es regnet, gehen wir spazieren.", options: ["Deshalb", "Weil", "Obwohl", "Wenn"], answer: 2 },
  { id: 3116, set: "B1.1", level: "B1", topic: "Perfekt mit „sein“", q: "Letztes Wochenende ___ wir nach Samarkand gefahren.", options: ["haben", "sind", "werden", "waren"], answer: 1 },
  { id: 3117, set: "B1.1", level: "B1", topic: "Wortschatz", q: "Was bedeutet „sich entscheiden“?", options: ["etwas vergessen", "eine Wahl treffen", "etwas kaufen", "etwas verlieren"], answer: 1 },
  { id: 3118, set: "B1.1", level: "B1", topic: "Wortschatz", q: "Was bedeutet „eine Erfahrung machen“?", options: ["etwas erleben und daraus lernen", "etwas bezahlen", "etwas verkaufen", "etwas erklären"], answer: 0 },
  { id: 3119, set: "B1.1", level: "B1", topic: "Wortschatz", q: "Wenn man eine neue Arbeitsstelle sucht, kann man sich bei einer Firma ___.", options: ["anmelden", "bewerben", "bedanken", "entschuldigen"], answer: 1 },
  { id: 3120, set: "B1.1", level: "B1", topic: "Wortschatz", q: "Was bedeutet „zuverlässig“?", options: ["Man kann sich auf eine Person verlassen.", "Eine Person kommt immer zu spät.", "Eine Person spricht sehr leise.", "Eine Person arbeitet nie."], answer: 0 },
  { id: 3121, set: "B1.1", level: "B1", topic: "Satzverbindung", q: "Ich hatte gestern viel zu tun, ___ konnte ich nicht mitkommen.", options: ["trotzdem", "deshalb", "obwohl", "aber"], answer: 1 },
  { id: 3122, set: "B1.1", level: "B1", topic: "Meinung äußern", q: "Du möchtest deine Meinung sagen. Welche Antwort passt?", options: ["Meiner Meinung nach ist Deutsch eine interessante Sprache.", "Wann beginnt der Unterricht?", "Ich war gestern zu Hause.", "Wo ist die nächste Apotheke?"], answer: 0 },
  { id: 3123, set: "B1.1", level: "B1", topic: "Einen Vorschlag machen", q: "Du möchtest mit deinen Freunden etwas unternehmen. Was passt?", options: ["Wie wäre es, wenn wir am Samstag ins Kino gehen?", "Ich bin gestern ins Kino gegangen.", "Der Film beginnt um acht Uhr.", "Ich mag diesen Schauspieler."], answer: 0 },
  { id: 3124, set: "B1.1", level: "B1", topic: "Höflich widersprechen", q: "Dein Freund sagt: „Deutsch ist sehr einfach.“ Du bist anderer Meinung. Was kannst du sagen?", options: ["Das stimmt genau.", "Da bin ich nicht ganz deiner Meinung.", "Natürlich hast du recht.", "Das sehe ich genauso."], answer: 1 },
  { id: 3125, set: "B1.1", level: "B1", topic: "Grund nennen", q: "„Warum lernst du Deutsch?“ — Was passt?", options: ["Deshalb lerne ich Deutsch.", "Trotzdem lerne ich Deutsch.", "Weil ich später in Deutschland studieren möchte.", "Obwohl ich Deutsch lerne."], answer: 2 },

  // ═══════════════════════════ B1.2 ═══════════════════════════
  { id: 3201, set: "B1.2", level: "B1", topic: "Perfekt / Präteritum", q: "Gestern ___ ich sehr müde.", options: ["bin", "war", "habe", "werde"], answer: 1 },
  { id: 3202, set: "B1.2", level: "B1", topic: "Konnektoren", q: "Ich lerne Deutsch, ___ ich später in Deutschland studieren möchte.", options: ["obwohl", "weil", "trotzdem", "deshalb"], answer: 1 },
  { id: 3203, set: "B1.2", level: "B1", topic: "Konnektoren", q: "Es regnet, ___ gehe ich spazieren.", options: ["weil", "obwohl", "trotzdem", "deshalb"], answer: 2 },
  { id: 3204, set: "B1.2", level: "B1", topic: "Konjunktiv II", q: "Ich ___ gern ein neues Handy kaufen.", options: ["würde", "werde", "wurde", "werde haben"], answer: 0 },
  { id: 3205, set: "B1.2", level: "B1", topic: "Relativsatz", q: "Das ist der Mann, ___ in Berlin arbeitet.", options: ["der", "den", "dem", "das"], answer: 0 },
  { id: 3206, set: "B1.2", level: "B1", topic: "Passiv", q: "Das Essen ___ jeden Tag frisch gekocht.", options: ["wird", "werden", "hat", "ist"], answer: 0 },
  { id: 3207, set: "B1.2", level: "B1", topic: "Indirekte Frage", q: "Ich weiß nicht, ___ er heute kommt.", options: ["ob", "dass", "weil", "trotzdem"], answer: 0 },
  { id: 3208, set: "B1.2", level: "B1", topic: "Wortschatz", q: "Was bedeutet „pünktlich“?", options: ["zu spät", "genau zur richtigen Zeit", "sehr schnell", "sehr langsam"], answer: 1 },
  { id: 3209, set: "B1.2", level: "B1", topic: "Wortschatz", q: "Wenn man eine Wohnung sucht, kann man eine ___ lesen.", options: ["Anzeige", "Prüfung", "Rechnung", "Einladung"], answer: 0 },
  { id: 3210, set: "B1.2", level: "B1", topic: "Redemittel", q: "Was passt zur eigenen Meinung?", options: ["Meiner Meinung nach ist das eine gute Idee.", "Gute Reise!", "Guten Appetit!", "Wie viel Uhr ist es?"], answer: 0 },
  { id: 3211, set: "B1.2", level: "B1", topic: "Konnektor", q: "Ich hatte keine Zeit, ___ konnte ich dich nicht anrufen.", options: ["aber", "deshalb", "obwohl", "weil"], answer: 1 },
  { id: 3212, set: "B1.2", level: "B1", topic: "Präposition", q: "Ich interessiere mich ___ Musik.", options: ["an", "für", "mit", "bei"], answer: 1 },
  { id: 3213, set: "B1.2", level: "B1", topic: "Reflexives Verb", q: "Wir ___ auf die Prüfung.", options: ["bereiten uns vor", "uns vorbereiten", "bereiten vor uns", "vorbereitet uns"], answer: 0 },
  { id: 3214, set: "B1.2", level: "B1", topic: "Konjunktiv II", q: "Wenn ich mehr Zeit hätte, ___ ich mehr Sport machen.", options: ["werde", "würde", "wurde", "bin"], answer: 1 },
  { id: 3215, set: "B1.2", level: "B1", topic: "Relativsatz", q: "Das ist die Stadt, ___ ich sehr gern besuche.", options: ["der", "die", "dem", "den"], answer: 1 },
  { id: 3216, set: "B1.2", level: "B1", topic: "Passiv", q: "In Deutschland ___ viele Autos produziert.", options: ["wird", "werden", "hat", "ist"], answer: 1 },
  { id: 3217, set: "B1.2", level: "B1", topic: "Wortschatz", q: "Was bedeutet „sich bewerben“?", options: ["einen Urlaub machen", "eine Stelle suchen und dafür Unterlagen schicken", "eine Wohnung mieten", "eine Prüfung machen"], answer: 1 },
  { id: 3218, set: "B1.2", level: "B1", topic: "Satzstruktur", q: "Welche Satzstruktur ist richtig?", options: ["Weil ich krank bin, bleibe ich heute zu Hause.", "Weil ich bin krank, bleibe ich heute zu Hause.", "Weil krank ich bin, bleibe heute ich zu Hause.", "Weil ich krank bin, ich bleibe heute zu Hause."], answer: 0 },
  { id: 3219, set: "B1.2", level: "B1", topic: "Indirekte Frage", q: "Welche Frage ist richtig?", options: ["Weißt du, wann der Kurs beginnt?", "Weißt du, wann beginnt der Kurs?", "Weißt du, wann der Kurs beginnt er?", "Weißt du, der Kurs wann beginnt?"], answer: 0 },
  { id: 3220, set: "B1.2", level: "B1", topic: "Satzstellung", q: "Ergänze den Satz: Obwohl ich müde bin, ___.", options: ["ich gehe ins Fitnessstudio", "gehe ich ins Fitnessstudio", "ich ins Fitnessstudio gehe", "ins Fitnessstudio ich gehe"], answer: 1 },
  { id: 3221, set: "B1.2", level: "B1", topic: "Satz ergänzen", q: "Ich lerne Deutsch, ___ ich später in Deutschland arbeiten möchte.", options: ["deshalb", "trotzdem", "weil", "obwohl"], answer: 2 },
  { id: 3222, set: "B1.2", level: "B1", topic: "Meinung äußern", q: "Du möchtest deine Meinung sagen. Was passt?", options: ["Ich denke, dass das eine gute Idee ist.", "Ich habe gestern gearbeitet.", "Wo ist der Bahnhof?", "Ich möchte einen Kaffee."], answer: 0 },
  { id: 3223, set: "B1.2", level: "B1", topic: "Höflich widersprechen", q: "Du bist mit einer Meinung nicht einverstanden. Was passt?", options: ["Genau, das sehe ich auch so.", "Da bin ich anderer Meinung.", "Das finde ich auch.", "Das stimmt genau."], answer: 1 },
  { id: 3224, set: "B1.2", level: "B1", topic: "Vorschlag", q: "Du möchtest einen Vorschlag machen. Was passt?", options: ["Wie wäre es, wenn wir am Wochenende ins Kino gehen?", "Ich war gestern im Kino.", "Das Kino ist geschlossen.", "Ich habe einen Film gesehen."], answer: 0 },
  { id: 3225, set: "B1.2", level: "B1", topic: "Grund nennen", q: "„Warum lernst du Deutsch?“ — Was passt?", options: ["Deshalb lerne ich Deutsch.", "Weil ich später in Deutschland studieren möchte.", "Trotzdem lerne ich Deutsch.", "Obwohl ich Deutsch lerne."], answer: 1 },

  // ═══════════════════════════ B2.1 ═══════════════════════════
  { id: 4101, set: "B2.1", level: "B2", topic: "Konjunktiv II — Gegenwart", q: "Wenn ich mehr Geld ___, würde ich eine längere Reise machen.", options: ["habe", "hätte", "hatte", "haben"], answer: 1 },
  { id: 4102, set: "B2.1", level: "B2", topic: "Konjunktiv II", q: "An deiner Stelle ___ ich mit dem Lehrer darüber sprechen.", options: ["werde", "würde", "werde ich", "hätte"], answer: 1 },
  { id: 4103, set: "B2.1", level: "B2", topic: "Plusquamperfekt", q: "Nachdem er die Prüfung ___, ging er nach Hause.", options: ["bestanden hat", "bestanden hatte", "besteht", "bestehen wird"], answer: 1 },
  { id: 4104, set: "B2.1", level: "B2", topic: "Nebensatz mit „während“", q: "___ ich früher mit dem Bus gefahren bin, fahre ich jetzt meistens mit dem Fahrrad.", options: ["Während", "Obwohl", "Deshalb", "Damit"], answer: 0 },
  { id: 4105, set: "B2.1", level: "B2", topic: "Konnektor", q: "Sie hatte keine Zeit, ___ konnte sie nicht an der Besprechung teilnehmen.", options: ["obwohl", "deshalb", "während", "damit"], answer: 1 },
  { id: 4106, set: "B2.1", level: "B2", topic: "„obwohl“", q: "___ er sehr gut vorbereitet war, war er vor der Prüfung nervös.", options: ["Weil", "Obwohl", "Deshalb", "Damit"], answer: 1 },
  { id: 4107, set: "B2.1", level: "B2", topic: "Infinitiv mit „zu“", q: "Ich habe vor, nächstes Jahr in Deutschland ___.", options: ["studieren", "zu studieren", "studiert", "studiere"], answer: 1 },
  { id: 4108, set: "B2.1", level: "B2", topic: "Präposition", q: "Ich interessiere mich sehr ___ moderne Technologien.", options: ["an", "für", "mit", "über"], answer: 1 },
  { id: 4109, set: "B2.1", level: "B2", topic: "Präposition", q: "Viele Studenten leiden ___ Prüfungsstress.", options: ["für", "über", "unter", "an"], answer: 2 },
  { id: 4110, set: "B2.1", level: "B2", topic: "Adjektivdeklination", q: "Wir suchen eine Wohnung mit einem groß___ Balkon.", options: ["-e", "-en", "-em", "-er"], answer: 1 },
  { id: 4111, set: "B2.1", level: "B2", topic: "Relativsatz", q: "Das ist der Kurs, ___ ich dir gestern erzählt habe.", options: ["der", "den", "von dem", "dessen"], answer: 2 },
  { id: 4112, set: "B2.1", level: "B2", topic: "Relativsatz", q: "Die Frau, ___ Sohn in Deutschland studiert, arbeitet bei uns.", options: ["die", "deren", "der", "dessen"], answer: 1 },
  { id: 4113, set: "B2.1", level: "B2", topic: "Passiv", q: "In diesem Gebäude ___ gerade neue Büros eingerichtet.", options: ["werden", "wurden", "haben", "sind"], answer: 0 },
  { id: 4114, set: "B2.1", level: "B2", topic: "Passiv mit Modalverb", q: "Die Bewerbung ___ bis Montag abgeschickt werden.", options: ["muss", "muss abgeschickt", "muss abgeschickt werden", "wird abgeschickt"], answer: 0 },
  { id: 4115, set: "B2.1", level: "B2", topic: "„um … zu“", q: "Er lernt jeden Abend Deutsch, ___ die B2-Prüfung erfolgreich zu bestehen.", options: ["damit", "um", "obwohl", "sodass"], answer: 1 },
  { id: 4116, set: "B2.1", level: "B2", topic: "„damit“", q: "Ich erkläre dir die Grammatik noch einmal, ___ du sie besser verstehen kannst.", options: ["um", "damit", "obwohl", "während"], answer: 1 },
  { id: 4117, set: "B2.1", level: "B2", topic: "Wortschatz", q: "Was bedeutet „eine Entscheidung treffen“?", options: ["eine Entscheidung vergessen", "eine Entscheidung machen", "sich für etwas entscheiden", "eine Entscheidung erklären"], answer: 2 },
  { id: 4118, set: "B2.1", level: "B2", topic: "Wortschatz", q: "Was bedeutet „eine Aufgabe erledigen“?", options: ["eine Aufgabe beginnen und nicht beenden", "eine Aufgabe erfolgreich fertig machen", "eine Aufgabe vergessen", "eine Aufgabe verschieben"], answer: 1 },
  { id: 4119, set: "B2.1", level: "B2", topic: "Wortschatz", q: "Was bedeutet „sich auf etwas verlassen können“?", options: ["etwas nicht verstehen", "jemandem oder etwas vertrauen können", "etwas vermeiden", "etwas ablehnen"], answer: 1 },
  { id: 4120, set: "B2.1", level: "B2", topic: "Passendes Verb", q: "Viele junge Menschen möchten nach der Schule Berufserfahrung ___.", options: ["nehmen", "sammeln", "machen", "bekommen"], answer: 1 },
  { id: 4121, set: "B2.1", level: "B2", topic: "Satzverbindung", q: "Er war krank. ___ ging er zur Arbeit.", options: ["Trotzdem", "Deshalb", "Weil", "Damit"], answer: 0 },
  { id: 4122, set: "B2.1", level: "B2", topic: "Satzbau", q: "Welche Variante ist grammatisch richtig?", options: ["Obwohl er hatte wenig Zeit, half er seinem Freund.", "Obwohl hatte er wenig Zeit, half er seinem Freund.", "Obwohl er wenig Zeit hatte, half er seinem Freund.", "Obwohl wenig Zeit er hatte, er half seinem Freund."], answer: 2 },
  { id: 4123, set: "B2.1", level: "B2", topic: "Meinung äußern", q: "Du möchtest deine Meinung zu einem Thema ausdrücken. Welche Aussage passt am besten?", options: ["Meiner Meinung nach sollte man dieses Problem ernst nehmen.", "Ich habe gestern lange gearbeitet.", "Wann beginnt der Kurs?", "Ich habe keine Zeit gehabt."], answer: 0 },
  { id: 4124, set: "B2.1", level: "B2", topic: "Höflich seine Meinung äußern", q: "Welche Formulierung klingt am höflichsten und passend für B2?", options: ["Das ist völlig falsch!", "Du hast keine Ahnung.", "Ich sehe das etwas anders und möchte einen anderen Aspekt hervorheben.", "Nein, das stimmt überhaupt nicht."], answer: 2 },
  { id: 4125, set: "B2.1", level: "B2", topic: "Vor- und Nachteile nennen", q: "Welche Aussage eignet sich am besten, um Vor- und Nachteile zu vergleichen?", options: ["Ich finde diese Idee interessant.", "Einerseits spart man Zeit, andererseits kann diese Lösung zusätzliche Kosten verursachen.", "Diese Lösung ist sehr interessant.", "Ich habe darüber schon einmal gesprochen."], answer: 1 },

  // ═══════════════════════════ B2.2 ═══════════════════════════
  { id: 4201, set: "B2.2", level: "B2", topic: "Konjunktiv II", q: "Wenn ich mehr Zeit ___, würde ich öfter reisen.", options: ["habe", "hätte", "hatte", "haben"], answer: 1 },
  { id: 4202, set: "B2.2", level: "B2", topic: "Konjunktiv II Vergangenheit", q: "Wenn ich früher losgegangen wäre, ___ ich den Zug erreicht.", options: ["habe", "hätte", "würde", "werde"], answer: 1 },
  { id: 4203, set: "B2.2", level: "B2", topic: "Passiv", q: "Die neuen Wohnungen ___ nächstes Jahr gebaut.", options: ["werden", "wurden", "haben", "sind"], answer: 0 },
  { id: 4204, set: "B2.2", level: "B2", topic: "Relativsatz", q: "Das ist die Kollegin, ___ ich gestern geholfen habe.", options: ["die", "der", "den", "deren"], answer: 1 },
  { id: 4205, set: "B2.2", level: "B2", topic: "Adjektivdeklination", q: "Er hat mit einem sehr freundlich___ Mann gesprochen.", options: ["-e", "-en", "-em", "-er"], answer: 1 },
  { id: 4206, set: "B2.2", level: "B2", topic: "Konnektor", q: "___ des schlechten Wetters fand das Konzert statt.", options: ["Obwohl", "Trotz", "Deshalb", "Während"], answer: 1 },
  { id: 4207, set: "B2.2", level: "B2", topic: "Wortschatz", q: "Was bedeutet „eine Lösung finden“?", options: ["ein Problem lösen", "ein Problem vergessen", "ein Problem wiederholen", "ein Problem erklären"], answer: 0 },
  { id: 4208, set: "B2.2", level: "B2", topic: "Wortschatz", q: "„Die Nachfrage nach Wohnungen ist gestiegen.“ Was bedeutet „Nachfrage“?", options: ["Interesse bzw. Bedarf an etwas", "Preis von etwas", "Größe von etwas", "Qualität von etwas"], answer: 0 },
  { id: 4209, set: "B2.2", level: "B2", topic: "Indirekte Rede", q: "Er sagt: „Ich komme morgen.“ → Er sagt, dass er am nächsten Tag ___.", options: ["kommt", "kommen wird", "gekommen ist", "kam"], answer: 0 },
  { id: 4210, set: "B2.2", level: "B2", topic: "Präposition + Genitiv", q: "___ der hohen Kosten haben wir das Projekt abgesagt.", options: ["Wegen", "Trotz", "Mit", "Bei"], answer: 0 },
  { id: 4211, set: "B2.2", level: "B2", topic: "Passiv mit Modalverb", q: "Die Rechnung ___ bis Freitag bezahlt werden.", options: ["muss", "muss werden", "muss bezahlt", "muss bezahlt werden"], answer: 0 },
  { id: 4212, set: "B2.2", level: "B2", topic: "Konzessivsatz", q: "___ er sehr müde war, arbeitete er weiter.", options: ["Obwohl", "Deshalb", "Trotzdem", "Wegen"], answer: 0 },
  { id: 4213, set: "B2.2", level: "B2", topic: "„Je … desto …“", q: "___ mehr Deutsch man spricht, ___ sicherer wird man.", options: ["Je … desto", "Wenn … dann", "Je … weil", "Obwohl … desto"], answer: 0 },
  { id: 4214, set: "B2.2", level: "B2", topic: "„sodass“", q: "Er hat sehr viel gelernt, ___ er die Prüfung bestehen konnte.", options: ["obwohl", "sodass", "während", "trotzdem"], answer: 1 },
  { id: 4215, set: "B2.2", level: "B2", topic: "Präposition", q: "Wir müssen uns ___ die neue Situation gewöhnen.", options: ["an", "auf", "über", "mit"], answer: 0 },
  { id: 4216, set: "B2.2", level: "B2", topic: "Wortschatz", q: "Was bedeutet „zuverlässig“?", options: ["Man kann sich auf jemanden verlassen.", "Jemand arbeitet sehr langsam.", "Jemand ist oft krank.", "Jemand spricht wenig."], answer: 0 },
  { id: 4217, set: "B2.2", level: "B2", topic: "Wortschatz", q: "Was bedeutet „eine Erfahrung sammeln“?", options: ["etwas vergessen", "Erfahrungen machen und daraus lernen", "etwas kaufen", "eine Prüfung schreiben"], answer: 1 },
  { id: 4218, set: "B2.2", level: "B2", topic: "Satzstruktur", q: "Welche Satzstruktur ist richtig?", options: ["Obwohl die Arbeit schwierig war, konnte er sie erfolgreich beenden.", "Obwohl die Arbeit war schwierig, konnte er sie erfolgreich beenden.", "Obwohl die Arbeit schwierig war, er konnte sie erfolgreich beenden.", "Obwohl schwierig die Arbeit war, konnte er sie beenden."], answer: 0 },
  { id: 4219, set: "B2.2", level: "B2", topic: "„Je … desto …“", q: "Welche Variante ist richtig?", options: ["Je länger man wartet, desto schwieriger wird die Situation.", "Je länger man wartet, desto die Situation schwieriger wird.", "Je länger wartet man, desto schwieriger die Situation wird.", "Je länger man wartet, desto wird die Situation schwieriger."], answer: 0 },
  { id: 4220, set: "B2.2", level: "B2", topic: "Genitiv", q: "Welche Variante ist richtig?", options: ["Aufgrund des starken Regens wurde das Spiel abgesagt.", "Aufgrund den starken Regen wurde das Spiel abgesagt.", "Aufgrund der starken Regen wurde das Spiel abgesagt.", "Aufgrund starkem Regen wurde das Spiel abgesagt."], answer: 0 },
  { id: 4221, set: "B2.2", level: "B2", topic: "Plusquamperfekt", q: "Welche Variante ist richtig?", options: ["Er hat die Prüfung bestanden, obwohl er nur wenig gelernt hatte.", "Er hat die Prüfung bestanden, obwohl hatte er nur wenig gelernt.", "Er hat die Prüfung bestanden, obwohl er hatte nur wenig gelernt.", "Er hat die Prüfung bestanden, obwohl nur wenig er gelernt hatte."], answer: 0 },
  { id: 4222, set: "B2.2", level: "B2", topic: "Meinung äußern", q: "Du möchtest deine Meinung ausdrücken. Was passt?", options: ["Meiner Ansicht nach hat diese Lösung mehr Vorteile als Nachteile.", "Ich habe gestern gearbeitet.", "Wo befindet sich der Bahnhof?", "Ich möchte einen Kaffee bestellen."], answer: 0 },
  { id: 4223, set: "B2.2", level: "B2", topic: "Höflich widersprechen", q: "Du möchtest höflich widersprechen. Was passt?", options: ["Das ist absolut falsch!", "Ich sehe das etwas anders, weil es auch andere Möglichkeiten gibt.", "Nein, das stimmt nicht!", "Du hast keine Ahnung."], answer: 1 },
  { id: 4224, set: "B2.2", level: "B2", topic: "Vorschlag", q: "Du möchtest einen Vorschlag machen. Was passt?", options: ["Ich würde vorschlagen, dass wir zunächst beide Möglichkeiten vergleichen.", "Ich habe gestern darüber gesprochen.", "Das ist schon lange bekannt.", "Ich kenne diese Möglichkeit."], answer: 0 },
];
